export default {
    "en": {
        "teams": {
            "system": "System",
            "swiss": "Swiss",
            "groups": "Groups (Round)",
            "supermele": "Supermele",
            "teams": "Teams",
            "games": "Current games",
            "results": "Results",
            "ranking": "Ranking",
            "tournamentId": "Tournament Id",
            "importPortal": "Import from portal",
            "teamTitle": "Team title",
            "addTeam": "Add team",
            "addTeamMessage": "add first team...",
            "useTeamRating": "Use team rating for drawing",
            "removeTournament": "Remove tournament",
            "alreadyArchived": "Tournament is already archived",
            "saveTournament": "Archive tournament",
            "startTournament": "Start tournament",
            "saveTournamentData": "Save data",
            "finishTournament": "Finish tournament",
            "finishTournamentConfirm": "Are you sure you want to finish the tournament?",
            "preferences": "Preferences",
            "rating": "Rating",
            "playersInTeam": "How many players in a team?",
            "teamsInGroup": "How many team in group?",
            "protocol": "protocol",
            "copyProtocol": "Copy protocol",
            "exportPdf": "Export to PDF",
            "restoreTeams": "Restore last teams",
            "searchTeam": "Search participant...",
            "noResults": "Not found"
        },
        "games": {
            "technical": "Technical",
            "draw": "Draw",
            "first": "First",
            "shuffleLanes": "Shuffle lanes",
            "show": "Show",
            "compact": "compact",
            "full": "full",
            "view": "view",
            "lane": "Lane",
            "lanesPlayed": "lanes",
            "saveResults": "Save results",
            "enterAllScores": "Enter all scores first",
            "resultsError": "Some results are missing or incorrect",
            "restoreRound": "Restore previous round",
            "restoreRoundConfirm": "Are you sure you want to restore the previous round? This action cannot be undone.",
            "noGames": "No games, yet",
            "quantityError": "Rounds quantity can't be more than teams",
            "drawError": "There was an unexpectable error, sorry for that, you can write developer about it (contact in footer), but this will not help you in this situation:))",
            "clickToDraw": "Please, click on button to draw",
            "thirdPlace": "3rd place",
            "final": "Final",
            "ofFinal": "final",
            "tournamentFinished": "Tournament has finished",
            "seeResult": "See result",
            "showBracket": "Show playoff bracket",
            "playOff": "PlayOff",
            "cadrage": "Cadrage",
            "someone": "Someone",
            "lucky": "Lucky guy",
            "chooseSystem": "Choose tournament system",
            "chooseSystemText": "Prohibited to play swiss system with less then 8 teams",
            "playMaximum": "You can play maximum ",
            "playNextCircle": "Play next circle",
            "circlesPlayed": "Circles played"
        },
        "results": {
            "title": "Every round results",
            "all": "All"
        },
        "ranking": {
            "ranking": "Ranking",
            "after": "after",
            "round": "round",
            "rounds": "rounds",
            "swiss": "swiss",
            "noRanking": "No ranking",
            "points": "Points",
            "pointsMobile": "P",
            "pointsTooltip": "Points scored : points conceded",
            "wins": "Wins",
            "winsMobile": "W",
            "team": "Team",
            "place": "Place",
            "rating": "Rating",
            "ratingMobile": "R",
            "difference": "Difference",
            "differenceMobile": "D",
            "player": "Player",
            "players": "Players",
            "sbuh": "SBuh",
            "sbuhMobile": "S",
            "sbuhTooltip": "Sum of Buchholz scores of all opponents",
            "buh": "Buh",
            "buhMobile": "B",
            "buhTooltip": "Sum of wins of all opponents",
            "roundsPlayed": "Rounds played",
            "tournamentResult": "Tournament Result",
            "swissTable": "Swiss table",
            "copyResults": "Copy results",
            "exportResults": "Export results",
            "exportConfirm": "Are you sure you want to export results to the FPU portal?",
            "goPlayOff": "Go to play-off?",
            "withCadrage": "With cadrage",
            "cadrageHint": "Extra round for teams on the edge of the playoff zone to compete for a spot",
            "chooseNumberTeams": "Choose number of teams",
            "go": "Go!",
            "alsoPlay": "Also play",
            "tournamentB": "Tournament B"
        },
        "remote": {
            "remoteAvailabilities": "Remote availabilities",
            "sendNotification": "Send update notification",
            "showLinks": "Show tournament links",
            "showLink": "Show link",
            "writeMessage": "Write a message",
            "hideMessage": "Hide the message",
            "messageSaved": "Message saved",
            "organizerMessage": "Organizer",
            "copyLink": "Copy link",
            "linkCopied": "Link copied to clipboard",
            "qrAndLink": "QR code and link for tournament"
        },
        "login": {
            "back": "Back",
            "email": "Enter email",
            "emailPlaceholder": "Email",
            "emailError": "Email is not correct",
            "password": "Enter password",
            "passwordPlaceholder": "Password",
            "confirmPlaceholder": "Confirm password",
            "passwordError": "Password is not correct",
            "forgot": "Forgot password?",
            "forgotHint": "Enter your email and we'll send you a reset link",
            "resetPassword": "Send reset link",
            "backToLogin": "Back to login",
            "loginTitle": "Welcome back",
            "loginBtn": "Sign in",
            "registerTitle": "Create account",
            "register": "Sign up",
            "justLogin": "Sign in",
            "noAccount": "Don't have an account?",
            "hasAccount": "Already have an account?",
            "newUser": "New User? Register here",
            "registerAccount": "Register new account"
        },
        "modals": {
            "sureRemove": "Are you sure you want to delete",
            "tournamentName": "Tournament name",
            "enterTournamentName": "Please, enter tournament name",
            "tournamentNameRequired": "Tournament name cannot be empty",
            "alreadyHaveName": "It seems you already have such tournament name",
            "resultsInTable": "Results in tables",
            "tournamentPreferences": "Tournament preferences",
            "maxScore": "Maximum score",
            "technicalScore": "Technical score",
            "technicalScoreHint": "Score awarded for a technical win (walkover)",
            "maxScoreHint": "Game ends when a team reaches this score",
            "playOffTeams": "How many team go to playoff?",
            "playOffTeamsHint": "Number of top teams advancing to the knockout stage",
            "playOffAlreadyStarted": "Cannot change — playoff has already started",
            "swissRoundsCount": "Number of Swiss rounds",
            "swissRoundsCountHint": "Informational — how many rounds are planned for this tournament",
            "prizePlaces": "Prize places",
            "prizePlacesHint": "Number of top teams highlighted in the ranking",
            "fieldsStart": "From which field should the numbering begin?",
            "fieldsStartHint": "First lane number (useful if your venue lanes start from a different number)",
            "timeLimit": "Time limit",
            "timeLimitHint": "Maximum game duration in minutes",
            "timeLimitSwiss": "Swiss rounds",
            "timeLimitPlayoff": "Playoff",
            "noTimeLimitFinale": "No time limit in finale",
            "cochonettes": "Additional cochonettes",
            "cochonettesHint": "Number of extra cochonettes per game",
            "min": "min",
            "removeHint": "This action cannot be undone"
        },
        "setup": {
            "readyToStart": "Tournament setup",
            "drawFirstRound": "Draw first round",
            "enablePlayOff": "Play-off after group stage",
            "additionalSettings": "Additional settings",
            "drawMethod": "Draw method",
            "drawMethodSeeded": "Seeded draw",
            "drawMethodSnake": "Snake seeding",
            "drawMethodBalanced": "Balanced random",
            "drawMethodSeededDesc": "Teams are split into rating pots. Each group gets one team from each pot.",
            "drawMethodSnakeDesc": "Teams are sorted by rating and distributed in a snake pattern.",
            "drawMethodBalancedDesc": "Several random draws are generated. The most balanced one is selected.",
            "drawMethodLearnMore": "How do these methods work?",
            "drawMethodModalTitle": "Draw methods",
            "drawMethodModalIntro": "These options use team rating strength to create fairer groups. You can choose between a classic seeded draw, automatic snake seeding, or a balanced random draw.",
            "drawMethodSeededFull": "Teams are split into rating pots. Each group gets one team from each pot. This is the most classic and transparent option.",
            "drawMethodSnakeFull": "Teams are sorted by rating and placed into groups in a snake pattern. This gives very balanced groups, but with less randomness.",
            "drawMethodBalancedFull": "The system generates many random draws and chooses the one where group rating totals are closest. This keeps randomness while improving balance.",
            "drawMethodBestFor": "Best for",
            "drawMethodSeededBest1": "Fair and transparent group draw",
            "drawMethodSeededBest2": "Keeping top teams separated",
            "drawMethodSeededBest3": "Preserving a real draw feeling",
            "drawMethodSnakeBest1": "Very balanced groups",
            "drawMethodSnakeBest2": "Fast automatic distribution",
            "drawMethodSnakeBest3": "Cases where randomness is less important",
            "drawMethodBalancedBest1": "Maximum balance while keeping randomness",
            "drawMethodBalancedBest2": "Avoiding \"group of death\" situations",
            "drawMethodBalancedBest3": "Making groups feel fair by total strength"
        },
        "common": {
            "updated": "has updated!",
            "swissCalculator": "Swiss system calculator",
            "group": "Group",
            "change": "Change",
            "cancel": "Cancel",
            "save": "Save",
            "remove": "Remove",
            "pin": "Pin as default",
            "unpin": "Unpin",
            "close": "Close",
            "menu": "Menu",
            "activeTournaments": "Active tournaments",
            "loginUser": "Log in as User",
            "logoutAdmin": "Logout as Admin",
            "logoutUser": "Logout",
            "language": "Language",
            "please": "Please,",
            "round": "Round",
            "or": "or",
            "developedBy": "Developed by",
            "onlyLoginMessage": "You can use this program only when login to the system as User",
            "addTournament": "Add new tournament",
            "adminSection": "Authorisation",
            "useful": "Petanque apps",
            "info": "Info",
            "settings": "Settings",
            "saved": "Saved tournaments",
            "archivedTournaments": "Archived tournaments",
            "choose": "Choose",
            "tournamentName": "Tournament name",
            "swissSystem": "About Swiss System",
            "howUse": "How to use",
            "portal": "FPU Portal",
            "show": "Show",
            "hide": "Hide",
            "games": "Games",
            "thankMe": "If you like to use this program, you can thank me here",
            "draw": "Draw",
            "stat": "Statistics",
            "training": "Training",
            "status": "Status",
            "active": "Active",
            "finished": "Finished",
            "notStarted": "Not started",
            "teamsCount": "Teams",
            "timeLimit": "Time limit",
            "cochonette": "cochonette",
            "cochonettes": "cochonettes",
            "places": "places",
            "teamsLabel": "teams",
            "darkTheme": "Dark theme",
            "lightTheme": "Light theme",
            "theme": "Theme"
        },
        "messages": {
            "sent": "Sent!",
            "checkEmail": "Check your email",
            "error": "Error",
            "somethingWrong": "Something went wrong",
            "missingEmail": "Missing email",
            "invalidEmail": "Invalid email",
            "noAccount": "No account with this email",
            "incorrectPassword": "Incorrect password",
            "passwordMismatch": "Passwords do not match",
            "weakPassword": "Password must be at least 6 characters",
            "cantDraw": "Can't draw",
            "someError": "Some error happened",
            "cantDrawRound": "Can't draw this round",
            "tooManyGames": "Too many games for swiss with this number of teams",
            "chooseCorrectTeams": "Choose correct number of teams in group",
            "success": "Success",
            "resultsSaved": "Your results saved",
            "teamExists": "Such team already registered! Change team title, please",
            "enterFields": "Enter fields to add team",
            "awesome": "Awesome!",
            "statsSaved": "Statistics saved",
            "failedLoadTags": "Failed to load tags",
            "exercisesLoaded": "Exercises successfully loaded",
            "noExercisesFound": "No exercises found for you",
            "info": "Info",
            "failedLoadData": "Failed to load data",
            "exerciseRemoved": "Exercise successfully removed",
            "notAllResults": "Not all results",
            "someAttemptsNotWritten": "Some attempts not written",
            "youAreOffline": "You are offline",
            "trainingSavedBrowser": "Your training saved in browser. Save it when you will be online",
            "exerciseSaved": "Exercise saved",
            "protocolCopied": "Protocol is in your buffer",
            "cantCopyProtocol": "Can't copy protocol",
            "tagSaved": "Tag saved",
            "tagUpdated": "Tag updated",
            "removed": "Removed",
            "tournamentRemoved": "Tournament has been removed",
            "notAvailable": "Not available",
            "maxTournaments": "You can make only 10 tournaments. Remove one to add new",
            "saved": "Saved",
            "tournamentSavedList": "You can see your saved tournaments in the menu",
            "tournamentRemovedSaved": "Tournament removed from your saved list",
            "tournamentDataSaved": "Tournament data saved",
            "failedSaving": "Something went wrong while saving",
            "removeExercise": "Remove this exercise?",
            "tournamentNotActive": "Tournament is not active",
            "noArchivedTournaments": "Your archived tournaments will appear here after you finish and save them",
            "gameRemoved": "Game successfully removed",
            "tagRemoved": "Tag successfully removed",
            "failedSaveData": "Failed to save data",
            "tournamentPinned": "This tournament will open by default",
            "tournamentUnpinned": "Tournament unpinned",
            "preferencesSaved": "Settings saved"
        }
    },
    "ua": {
        "teams": {
            "system": "Система",
            "swiss": "Швейцарка",
            "groups": "Групи (Кругова)",
            "supermele": "Супермеле",
            "teams": "Команди",
            "games": "Поточні ігри",
            "results": "Результати",
            "ranking": "Таблиця",
            "tournamentId": "Id турніру",
            "importPortal": "Імпортувати з порталу",
            "teamTitle": "Назва команди",
            "addTeam": "Додати",
            "addTeamMessage": "додайте першу команду...",
            "useTeamRating": "Використовувати рейтинг під час жеребкування",
            "removeTournament": "Видалити турнір",
            "alreadyArchived": "Турнір вже архівовано",
            "saveTournament": "Архівувати турнір",
            "startTournament": "Старт",
            "saveTournamentData": "Зберегти дані",
            "finishTournament": "Закінчити турнір",
            "finishTournamentConfirm": "Ви впевнені, що хочете закінчити турнір?",
            "preferences": "Налаштування турніру",
            "rating": "Рейтинг",
            "playersInTeam": "Скільки гравців у команді?",
            "teamsInGroup": "Скільки команд у групі?",
            "protocol": "протокол",
            "copyProtocol": "Скопіювати протокол",
            "exportPdf": "Експортувати в PDF",
            "restoreTeams": "Відновити останні команди",
            "searchTeam": "Шукати учасника...",
            "noResults": "Не знайдено"
        },
        "remote": {
            "remoteAvailabilities": "Можливості для віддаленого керування",
            "sendNotification": "Надіслати сповіщення про оновлення турніру",
            "showLinks": "Показати посилання на турнір",
            "showLink": "Посилання",
            "writeMessage": "Написати повідомлення",
            "hideMessage": "Сховати повідомлення",
            "messageSaved": "Повідомлення збережено",
            "organizerMessage": "Організатор",
            "copyLink": "Скопіювати посилання",
            "linkCopied": "Посилання скопійовано",
            "qrAndLink": "QR код та посилання на турнір"
        },
        "games": {
            "technical": "Технічна",
            "draw": "Жеребкувати",
            "first": "Перший",
            "shuffleLanes": "Перемішати доріжки",
            "show": "Показати",
            "compact": "компактний",
            "full": "повний",
            "view": "вигляд",
            "lane": "Доріжка",
            "lanesPlayed": "доріжки",
            "saveResults": "Зберегти результати",
            "enterAllScores": "Спочатку введіть всі результати",
            "resultsError": "Не всі результати заповнені або містять помилки",
            "restoreRound": "Відновити попередній раунд",
            "restoreRoundConfirm": "Ви впевнені, що хочете відновити попередній раунд? Цю дію неможливо скасувати.",
            "noGames": "Поки що ігор немає",
            "quantityError": "Кількість раундів не може бути більшою за кількість команд",
            "drawError": "Сталася непередбачувана помилка при жеребкуванні. Дуже шкода. Ви можете написати розробнику про це (контакт внизу сторінки), але конкретно в цій ситуації це вам не допоможе:))",
            "clickToDraw": "Натисніть кнопку, щоб пожеребкувати",
            "thirdPlace": "3 місце",
            "final": "Фінал",
            "ofFinal": "фіналу",
            "tournamentFinished": "Турнір завершено",
            "seeResult": "Подивитися результати",
            "showBracket": "Показати сітку плей-офф",
            "playOff": "Плей офф",
            "cadrage": "Кадраж",
            "someone": "Якийсь",
            "lucky": "щасливчик",
            "chooseSystem": "Виберіть систему розіграшу",
            "chooseSystemText": "Забороняється грати турнір по швейцарській системі при кількості команд менше 8",
            "playMaximum": "Ви можете зіграти максимум",
            "playNextCircle": "Зіграти наступне коло",
            "circlesPlayed": "Зіграно кіл"
        },
        "results": {
            "title": "Результати кожного раунду",
            "all": "Всі"
        },
        "ranking": {
            "ranking": "Таблиця",
            "after": "після",
            "round": "раунду",
            "swiss": "швейцарки",
            "rounds": "раундів",
            "noRanking": "Ще нема результатів",
            "points": "Очки",
            "pointsMobile": "О",
            "pointsTooltip": "Набрані очки : пропущені очки",
            "wins": "Перемоги",
            "winsMobile": "П",
            "team": "Команда",
            "place": "Місце",
            "rating": "Рейтинг",
            "ratingMobile": "Р",
            "difference": "Різниця очок",
            "differenceMobile": "РО",
            "player": "Гравець",
            "players": "Гравці",
            "sbuh": "Малий бухгольць",
            "sbuhMobile": "МБ",
            "sbuhTooltip": "Сума бухгольців усіх суперників",
            "buh": "Коеф. бухгольця",
            "buhMobile": "Б",
            "buhTooltip": "Сума перемог усіх суперників",
            "roundsPlayed": "Зіграно раундів",
            "tournamentResult": "Результати турніру",
            "swissTable": "Таблиця швейцарки",
            "copyResults": "Скопіювати результати",
            "exportResults": "Експортувати результати",
            "exportConfirm": "Ви впевнені, що хочете експортувати результати на портал ФПУ?",
            "goPlayOff": "Почати плей-оф?",
            "withCadrage": "З кадражем",
            "cadrageHint": "Додатковий раунд для команд на межі плей-офф зони, щоб розіграти місце",
            "chooseNumberTeams": "Оберіть скільки команд зіграє плей-офф",
            "go": "Погнали!",
            "alsoPlay": "Також зіграємо",
            "tournamentB": "Турнір Б"
        },
        "login": {
            "back": "Повернутися",
            "email": "Введіть електронну адресу",
            "emailPlaceholder": "Email",
            "emailError": "Адреса не корректна",
            "password": "Введіть пароль",
            "passwordPlaceholder": "Пароль",
            "confirmPlaceholder": "Підтвердьте пароль",
            "passwordError": "Пароль не вірний",
            "forgot": "Забули пароль?",
            "forgotHint": "Введіть email і ми надішлемо посилання для скидання",
            "resetPassword": "Надіслати посилання",
            "backToLogin": "Повернутися до входу",
            "loginTitle": "Вхід",
            "loginBtn": "Увійти",
            "registerTitle": "Створити акаунт",
            "register": "Зареєструватися",
            "justLogin": "Увійти",
            "noAccount": "Немає акаунту?",
            "hasAccount": "Вже є акаунт?",
            "newUser": "Новий користувач? Зареєструватися можна тут",
            "registerAccount": "Зареєструвати нового користувача"
        },
        "modals": {
            "sureRemove": "Ви впевнені, що хочете видалити турнір",
            "tournamentName": "Назва турніру",
            "enterTournamentName": "Введіть нову назву турніру",
            "tournamentNameRequired": "Назва турніру не може бути порожньою",
            "alreadyHaveName": "Здається вже є турнір з такою назвою",
            "resultsInTable": "Результати в таблицях",
            "tournamentPreferences": "Налаштування турніру",
            "maxScore": "Максимально можливий рахунок",
            "technicalScore": "Рахунок для технічної перемоги",
            "technicalScoreHint": "Рахунок, який присвоюється за технічну перемогу (неявка)",
            "maxScoreHint": "Гра завершується, коли команда досягає цього рахунку",
            "playOffTeams": "Скільки команд виходять у плей-офф?",
            "playOffTeamsHint": "Кількість найкращих команд, які проходять у етап на виліт",
            "playOffAlreadyStarted": "Неможливо змінити — плей-офф вже розпочато",
            "swissRoundsCount": "Кількість швейцарських раундів",
            "swissRoundsCountHint": "Інформаційно — скільки раундів заплановано для цього турніру",
            "prizePlaces": "Призові місця",
            "prizePlacesHint": "Кількість найкращих команд, що виділяються у рейтингу",
            "fieldsStart": "З якого майданчика починати нумерацію?",
            "fieldsStartHint": "Перший номер майданчика (корисно, якщо нумерація на вашому місці починається з іншого числа)",
            "timeLimit": "Обмеження часу",
            "timeLimitHint": "Максимальна тривалість гри в хвилинах",
            "timeLimitSwiss": "Швейцарські раунди",
            "timeLimitPlayoff": "Плей-офф",
            "noTimeLimitFinale": "Без обмеження часу у фіналі",
            "cochonettes": "Додаткові кошонети",
            "cochonettesHint": "Кількість додаткових кошонетів на гру",
            "min": "хв",
            "removeHint": "Цю дію неможливо скасувати"
        },
        "setup": {
            "readyToStart": "Налаштування турніру",
            "drawFirstRound": "Жеребкувати перший раунд",
            "enablePlayOff": "Плей-офф після групового етапу",
            "additionalSettings": "Додаткові налаштування",
            "drawMethod": "Метод жеребкування",
            "drawMethodSeeded": "Посів",
            "drawMethodSnake": "Змійка",
            "drawMethodBalanced": "Збалансований",
            "drawMethodSeededDesc": "Команди розподіляються на корзини за рейтингом. Кожна група отримує по команді з кожної корзини.",
            "drawMethodSnakeDesc": "Команди сортуються за рейтингом і розподіляються змійкою.",
            "drawMethodBalancedDesc": "Генерується багато випадкових розподілів і обирається найбільш збалансований.",
            "drawMethodLearnMore": "Як працюють ці методи?",
            "drawMethodModalTitle": "Методи жеребкування",
            "drawMethodModalIntro": "Ці методи використовують рейтинг команд для створення більш справедливих груп. Ви можете обрати класичний посів, автоматичну змійку або збалансоване випадкове жеребкування.",
            "drawMethodSeededFull": "Команди розподіляються на корзини за рейтингом. Кожна група отримує по команді з кожної корзини. Це найбільш класичний і прозорий варіант.",
            "drawMethodSnakeFull": "Команди сортуються за рейтингом і розміщуються в групи змійкою. Це дає дуже збалансовані групи, але з меншою випадковістю.",
            "drawMethodBalancedFull": "Система генерує багато випадкових розподілів і обирає той, де сумарний рейтинг груп найбільш рівний. Це зберігає випадковість, покращуючи баланс.",
            "drawMethodBestFor": "Найкраще для",
            "drawMethodSeededBest1": "Чесне і прозоре жеребкування",
            "drawMethodSeededBest2": "Розведення топ-команд",
            "drawMethodSeededBest3": "Збереження відчуття справжнього жеребкування",
            "drawMethodSnakeBest1": "Дуже збалансовані групи",
            "drawMethodSnakeBest2": "Швидкий автоматичний розподіл",
            "drawMethodSnakeBest3": "Коли випадковість менш важлива",
            "drawMethodBalancedBest1": "Максимальний баланс зі збереженням випадковості",
            "drawMethodBalancedBest2": "Уникнення \"групи смерті\"",
            "drawMethodBalancedBest3": "Справедливі групи за сумарною силою"
        },
        "common": {
            "updated": "оновлено!",
            "swissCalculator": "Калькулятор швейцарки",
            "group": "Група",
            "change": "Змінити",
            "cancel": "Відмінити",
            "save": "Зберегти",
            "pin": "Закріпити",
            "unpin": "Відкріпити",
            "remove": "Видалити",
            "close": "Зачинити",
            "menu": "Меню",
            "activeTournaments": "Активні турніри",
            "loginUser": "Увійти як користувач",
            "logoutAdmin": "Вийти як адміністратор",
            "logoutUser": "Вийти",
            "language": "Мова",
            "please": "Будь ласка,",
            "round": "Раунд",
            "or": "або",
            "developedBy": "Розроблено",
            "onlyLoginMessage": "Ви можете використовувати цю програму тільки коли увійдете в систему як користувач",
            "addTournament": "Додати новий турнір",
            "adminSection": "Авторизація",
            "useful": "Програми для петанку",
            "info": "Інформація",
            "settings": "Налаштування",
            "saved": "Збережені турніри",
            "archivedTournaments": "Архів турнірів",
            "choose": "Виберіть",
            "tournamentName": "Назва турніру",
            "swissSystem": "Про швейцарську систему",
            "howUse": "Інструкція",
            "portal": "Портал ФПУ",
            "show": "Показати",
            "hide": "Cховати",
            "games": "Ігри",
            "thankMe": "Якщо вам подобається користуватися цією програмкою, можете подякувати мені тут",
            "draw": "Жеребкування",
            "stat": "Статистика",
            "training": "Тренування",
            "status": "Статус",
            "active": "Активний",
            "finished": "Завершений",
            "notStarted": "Не розпочато",
            "teamsCount": "Команди",
            "timeLimit": "Обмеження часу",
            "cochonette": "кошонет",
            "cochonettes": "кошонети",
            "places": "місця",
            "teamsLabel": "команд",
            "darkTheme": "Темна тема",
            "lightTheme": "Світла тема",
            "theme": "Тема"
        },
        "messages": {
            "sent": "Надіслано!",
            "checkEmail": "Перевірте вашу пошту",
            "error": "Помилка",
            "somethingWrong": "Щось пішло не так",
            "missingEmail": "Введіть email",
            "invalidEmail": "Невірний email",
            "noAccount": "Немає акаунту з таким email",
            "incorrectPassword": "Невірний пароль",
            "passwordMismatch": "Паролі не збігаються",
            "weakPassword": "Пароль має бути не менше 6 символів",
            "cantDraw": "Неможливо жеребкувати",
            "someError": "Сталася помилка",
            "cantDrawRound": "Неможливо жеребкувати цей раунд",
            "tooManyGames": "Забагато ігор для швейцарки з такою кількістю команд",
            "chooseCorrectTeams": "Оберіть правильну кількість команд у групі",
            "success": "Успішно",
            "resultsSaved": "Ваші результати збережено",
            "teamExists": "Така команда вже зареєстрована! Змініть назву команди",
            "enterFields": "Заповніть поля для додавання команди",
            "awesome": "Чудово!",
            "statsSaved": "Статистику збережено",
            "failedLoadTags": "Не вдалося завантажити теги",
            "exercisesLoaded": "Вправи успішно завантажено",
            "noExercisesFound": "Не знайдено вправ",
            "info": "Інформація",
            "failedLoadData": "Не вдалося завантажити дані",
            "exerciseRemoved": "Вправу успішно видалено",
            "notAllResults": "Не всі результати",
            "someAttemptsNotWritten": "Деякі спроби не записані",
            "youAreOffline": "Ви офлайн",
            "trainingSavedBrowser": "Ваше тренування збережено в браузері. Збережіть його, коли будете онлайн",
            "exerciseSaved": "Вправу збережено",
            "protocolCopied": "Протокол скопійовано в буфер",
            "cantCopyProtocol": "Не вдалося скопіювати протокол",
            "tagSaved": "Тег збережено",
            "tagUpdated": "Тег оновлено",
            "removed": "Видалено",
            "tournamentRemoved": "Турнір видалено",
            "notAvailable": "Недоступно",
            "maxTournaments": "Ви можете створити максимум 10 турнірів. Видаліть один, щоб додати новий",
            "saved": "Збережено",
            "tournamentSavedList": "Збережені турніри можна знайти в меню",
            "tournamentRemovedSaved": "Турнір видалено зі збережених",
            "tournamentDataSaved": "Дані турніру збережено",
            "failedSaving": "Помилка при збереженні",
            "removeExercise": "Видалити цю вправу?",
            "tournamentNotActive": "Турнір не активний",
            "noArchivedTournaments": "Ваші архівовані турніри з'являться тут після того, як ви їх завершите та збережете",
            "gameRemoved": "Гру успішно видалено",
            "tagRemoved": "Тег успішно видалено",
            "failedSaveData": "Не вдалося зберегти дані",
            "tournamentPinned": "Цей турнір буде відкриватись за замовчуванням",
            "tournamentUnpinned": "Турнір відкріплено",
            "preferencesSaved": "Налаштування збережено"
        }
    }
}
