export default {
    en: {
        teams: {
            system: 'System',
            swiss: 'Swiss',
            groups: 'Groups (Round)',
            supermele: 'Supermele',
            teams: 'Teams',
            games: 'Current games',
            results: 'Results',
            ranking: 'Ranking',
            tournamentId: 'Tournament Id',
            importPortal: 'Import from portal',
            teamTitle: 'Team title',
            addTeam: 'Add team',
            addTeamMessage: 'add first team...',
            useTeamRating: 'Use team rating for drawing',
            removeTournament: 'Remove tournament',
            saveTournament: 'Save tournament',
            finishTournament: 'Finish tournament',
            preferences: 'Preferences',
            currentList: 'Current list',
            rating: 'Rating',
            playersInTeam: 'How many players in a team?',
            teamsInGroup: 'How many team in group?',
            protocol: 'protocol',
            copyProtocol: 'Copy protocol',
            exportPdf: 'Export to PDF',
            restoreTeams: 'Restore last teams',
        },
        games: {
            draw: 'Draw',
            first: 'First',
            shuffleLanes: 'Shuffle lanes',
            show: 'Show',
            compact: 'compact',
            full: 'full',
            view: 'view',
            lane: 'Lane',
            saveResults: 'Save results',
            resultsError: 'Something wrong in games results',
            restoreRound: 'Restore previous round',
            noGames: 'No games, yet',
            quantityError: 'Rounds quantity can\'t be more than teams',
            drawError: 'There was an unexpectable error, sorry for that, you can write developer about it (contact in footer), but this will not help you in this situation:))',
            clickToDraw: 'Please, click on button to draw',
            thirdPlace: 'Game for 3d place',
            final: 'Final',
            ofFinal: 'final',
            tournamentFinished: 'Tournament has finished',
            seeResult: 'See result',
            showBracket: 'Show playoff bracket',
            playOff: 'PlayOff',
            someone: 'Someone',
            lucky: 'Lucky guy',
            chooseSystem: 'Choose tournament system',
            chooseSystemText: 'Prohibited to play swiss system with less then 8 teams',
        },
        results: {
            title: 'Every round results',
        },
        ranking: {
            ranking: 'Ranking',
            after: 'after',
            round: 'round',
            rounds: 'rounds',
            swiss: 'swiss',
            noRanking: 'No ranking',
            points: 'Points',
            pointsMobile: 'P',
            wins: 'Wins',
            winsMobile: 'W',
            team: 'Team',
            place: 'Place',
            rating: 'Rating',
            ratingMobile: 'R',
            difference: 'Difference',
            differenceMobile: 'D',
            player: 'Player',
            players: 'Players',
            sbuh: 'SBuh',
            sbuhMobile: 'S',
            buh: 'Buh',
            buhMobile: 'B',
            tournamentResult: 'Tournament Result',
            copyResults: 'Copy results',
            goPlayOff: 'Go to play-off?',
            chooseNumberTeams: 'Choose number of teams',
            go: 'Go!',
            alsoPlay: 'Also play',
            tournamentB: 'Tournament B',
        },
        remote: {
            remoteAvailabilities: 'Remote availabilities',
            sendNotification: 'Send update notification',
            showLinks: 'Show tournament links',
            writeMessage: 'Write a message',
            hideMessage: 'Hide the message',
            copyLink: 'Copy link',
            qrAndLink: 'QR code and link for tournament',
        },
        login: {
            back: 'Back',
            email: 'Enter email',
            emailError: 'Email is not correct',
            password: 'Enter password',
            passwordError: 'Password is not correct',
            forgot: 'Forgot password? Reset it',
            registerAccount: 'Register new account',
            register: 'Register me',
            justLogin: 'Just Log in me',
            newUser: 'New User? Register here',
        },
        modals: {
            sureRemove: 'Are you sure you want to delete',
            tournamentName: 'Tournament name',
            enterTournamentName: 'Please, enter tournament name',
            alreadyHaveName: 'It seems you already have such tournament name',
            resultsInTable: 'Results in tables',
            tournamentPreferences: 'Tournament preferences',
            maxScore: 'Maximum score',
            technicalScore: 'Technical score',
        },
        common: {
            group: 'Group',
            change: 'Change',
            cancel: 'Cancel',
            save: 'Save',
            remove: 'Remove',
            close: 'Close',
            menu: 'Menu',
            activeTournaments: 'Active tournaments',
            loginAdmin: 'Log in as Admin',
            loginUser: 'Log in as User',
            logoutAdmin: 'Logout as Admin',
            logoutUser: 'Logout as User',
            language: 'Language',
            please: 'Please,',
            round: 'Round',
            developedBy: 'Developed by',
            onlyLoginMessage: 'You can use this program only when login to the system as User',
            addTournament: 'Add new tournament',
            adminSection: 'Authorisation',
            useful: 'Useful links',
            info: 'Info',
            saved: 'Saved tournaments',
            choose: 'Choose',
            swissSystem: 'About Swiss System',
            howUse: 'How to use this program',
            portal: 'Ukrainian Petanque',
            show: 'Show',
            hide: 'Hide',
            games: 'Games',
            thankMe: 'If you like to use this program, you can thank me here',
            draw: 'Draw',
            stat: 'Statistics',
            training: 'Training'
        },
        help: {
            title: 'Tournament Drawing App for Petanque',
            description: 'This app simplifies the lives of petanque players who organize tournaments, cheer for their favorite team, or participate in competitions. All you need for drawing is internet access. Players no longer need to gather around the organizer’s table to find out their playing field, opponents, or their position in the standings. Now, they can simply follow a link on their phone to check everything online.',
            feature1: 'The app supports Swiss, round-robin, knockout systems, and supermelee.',
            feature2: 'Minimal settings.',
            feature3: 'Simple interface (or so I believe).',
            feature4: 'Ability to remotely view the current tournament status.',
            feature5: 'Precise drawing algorithm for the Swiss system. The app doesn’t draw teams randomly. For example, if the top 6 teams have the same number of wins, in the next round they will play as follows: 1-6, 2-5, 3-4.',
            howToUseTitle: 'How to Use This App',
            howToUse1: 'To use the app, you need to register an account. No personal data other than email is required (and even that remains private, not even visible to me, the developer).',
            howToUse2: 'Users can use the app as administrators (available only for Ukrainian users). This allows importing players from the Ukrainian Federation portal. I can issue a password personally upon request.',
            shortTitle: 'Quick Start Guide',
            shortText: 'To conduct a standard Swiss system tournament + playoffs, you need to:',
            shortText1: 'Log in as a user.',
            shortText2: 'Add team names on the "Teams" tab.',
            shortText3: 'Go to the "Current Games" tab and draw the first round.',
            shortText4: 'Enter the results and save them.',
            shortText5: 'Draw subsequent rounds as many as you wish to play.',
            shortText6: 'Go to the "Standings" tab to check the results (if interested).',
            shortText7: 'Select the number of teams for the playoffs and click "Let’s Go".',
            shortText8: 'Enter all results again on the "Current Games" tab.',
            shortText9: 'Once you input the final results, the tournament is completed. You can save it in your account for history or remove it from current tournaments.',
            shortSummary: 'Continue reading for more details.',
            interfaceTitle: 'Main Interface',
            interface1: 'Click on the title to change the tournament name.',
            interface2: 'Select the system for the tournament.',
            interface3: 'Admins only: Import teams from the UFP portal. Enter the last digits from the portal’s tournament URL (e.g.,',
            interface4: 'Team name (e.g., captain’s last name) will be added to the team list upon clicking "Add team".',
            interface5: 'Option to use rankings for the first round draw.',
            tournamentControlsTitle: 'Tournament Management',
            tournamentControls1: 'Basic options: configure, save, complete, or delete the tournament.',
            tournamentControls2: 'You can only save a tournament once it’s completed. A tournament is completed when the final results are entered or the "Complete Tournament" button is clicked.',
            tournamentControls3: 'The "Restore Last Teams" button is helpful if you’ve drawn the first round and realize you forgot to add or need to remove a team. Create a new tournament and click this button. Teams from the previous tournament will be available. See the last section of this guide for details on creating a new tournament.',
            mainTabs: 'Main Sections',
            mainTabs1: 'Team list: add or remove teams (before drawing the first round or anytime for supermelee).',
            mainTabs2: 'Current draw and result entry.',
            mainTabs3: 'Results of all games played.',
            mainTabs4: 'Final standings after each round and the overall tournament results.',
            preferences: 'Those "Minimal Settings"',
            preferences1: 'These settings are entirely optional.',
            preferences2: 'Occasionally, you might need to adjust the result of a technical victory. You can do this here.',
            preferences3: 'This setting can be useful for club tournaments, where a score of 31:0 is possible.',
            drawResults: 'Draw and Results',
            drawResultsText: 'This is the most important button. It generates opponents for each subsequent round. The app doesn’t ask for the total number of rounds. You won’t be able to draw more rounds than the number of teams. However, in the Swiss system, be cautious with small team counts and many rounds. At some point, the app won’t be able to satisfy all Swiss system conditions and won’t pair teams. This could happen, for example, with 7 rounds and 12 teams or 5 rounds and 8 teams. Plan carefully when running such tournaments.',
            drawResults1: 'Button to shuffle lanes. The app doesn’t track if a team plays multiple games on the same lane. This is useful for small tournaments (lane assignments are random except in playoffs).',
            drawResults2: 'Compact view of current games, available only on mobile devices.',
            drawResults3: 'Key button! If you make a mistake entering results, you can edit the previous round. This button appears after the next round is drawn. You can restore ONLY previous round.',
            ranking: 'Ranking',
            rankingSwiss1: 'Standings for the Swiss system are determined by these criteria:',
            rankingSwiss2: 'Number of wins.',
            rankingSwiss3: 'Buchholz coefficient (sum of opponents’ wins).',
            rankingSwiss4: 'Minor Buchholz coefficient (sum of opponents’ Buchholz).',
            rankingSwiss5: 'Points difference (scored vs. conceded).',
            rankingSwiss6: 'After each round, you can switch to a knockout tournament. Choose the top teams to generate a playoff bracket.',
            rankingSwiss7: 'If this box is checked, a new tournament with non-playoff teams will be generated automatically.',
            rankingRound1: 'Standings for the round-robin system are determined by:',
            rankingRound2: 'Number of wins.',
            rankingRound3: 'Head-to-head result (if teams played each other).',
            rankingRound4: 'Overall point difference across all games.',
            rankingRound5: 'If three or more teams are tied, ranking is determined by:',
            rankingRound6: 'Wins within the group of tied teams.',
            rankingRound7: 'Point difference within the group of tied teams.',
            rankingRound8: 'Overall point difference across all games.',
            playOff: 'Playoffs',
            playOffText: 'For knockout tournaments, view the playoff bracket on the "Current Games" tab. The app supports up to 64 teams in a knockout bracket.',
            roundSystem: 'Round-Robin System',
            roundSystemText: 'For round-robin tournaments, you can automatically split teams into groups. Select the number of teams per group (the system rounds off the number of groups). If no groups are planned, select the total registered teams.',
            roundSystemText1: 'I recommend using groups only if you can have equal numbers of teams in each group.',
            remoteControl: 'Remote Control',
            remoteControl1: 'One of the key features of the app (idea by Oleksandr Koval) is the ability for anyone to view current draws and results. All they need is the tournament link.',
            remoteControl2: 'Open the generated tournament link. Share it with participants or fans.',
            remoteControl3: 'You can post a message visible to everyone who visits the link. Use it to share tournament details, timings, or well wishes.',
            remoteView: 'Remote Viewing',
            remoteViewText: 'With the generated link, viewers can see:',
            remoteView1: 'Message from the tournament organizer.',
            remoteView2: 'Current games.',
            remoteView3: 'All previous results.',
            remoteView4: 'Final standings.',
            finishedTournament: 'Completed Tournament',
            finishedTournament1: 'After the tournament is completed, final results will appear on the "Ranking" tab.',
            finishedTournament2: 'You can save the tournament results, which remain available in the menu until deleted.',
            finishedTournament3: 'Use the "Copy Results" button to copy tournament results in text format to share via messenger.',
            tournamentsControlsTitle: 'Tournament Management',
            tournamentsControls1: 'Add a new tournament to the current list.',
            tournamentsControls2: 'Switch between tournaments here (or in the mobile menu, if using phone).',
            tournamentsControls3: 'You can manage up to 10 tournaments simultaneously. Delete outdated ones as needed.',
            thanksMessage: 'Thank you for your time. Send questions, comments, and suggestions to',
            thanksMessagePost: 'email',
            thanksMessageOr: 'or',
            thanksMessageMessenger: 'messenger',
            pressBtnSeeInterface: 'Press this button to see the interface:',
        },
        stat: {
            archive: 'Archive',
            enterName: 'Enter game name',
            mode: 'Mode',
            scenario: 'Scenario',
            system: 'System',
            team: 'Team',
            add: 'Add',
            classic: 'Classic',
            fast: 'Fast',
            simple: 'Simple',
            french: 'French (A, B, ...)',
            positive: 'Positive',
            negative: 'Negative',
            asCouch: 'As couch',
            start: 'Start',
            prev: 'Prev',
            next: 'Next',
            newGame: 'New game',
            finishGame: 'Finish game',
            removeMan: 'Remove this round',
            score: 'Score',
            man: 'Round',
            back: 'Back',
            analysis: 'analysis',
            everyManRes: 'Every round result',
            resBoules: 'Мен',
            winBoules: 'Мен',
            series: 'Series',
            all: 'All',
            points: 'Points',
            tirs: 'Tirs',
            howManyPoints: 'Enter how many points team won',
            onlyLogin: 'You can count statistic only as login user',
            total: 'Total',
            changePlayer: 'Change player',
            enterPlayerName: 'Enter player name',
            nothingShow: 'Nothing to show',
            findPlayer: 'Find Player',
            choosePeriod: 'Choose period',
            chooseOnly: 'Choose only',
            clear: 'Clear',
            noStat: 'No statistics with your filters',
        },
        training: {
            addEx: 'Add exercise',
            exList: 'Exercises list',
            toList: 'To list',
            serieLength: 'serie length',
            distances: 'distances',
            asLogin: 'You can count trainings statistic only as login user',
            addExToBegin: 'Add exercise to begin trainings',
            viewResults: 'View results',
            startTraining: 'Start training',
            enterExName: 'Enter training exercise name',
            serieQuantity: 'Serie quantity',
            nameSerie: 'Name every serie?',
            throwValue: 'Throw value',
            logical: 'Logical',
            exScenario: 'Exercise scenario',
            distFirst: 'Distance first',
            finishTraining: 'Finish training',
            attempt: 'attempt',
            meters: 'meters',
            noResults: 'No results',
            distance: 'Distance',
            exGradedText: 'This exercise is graded by points scored, not percentages',
        }
    },
    ua: {
        teams: {
            system: 'Система',
            swiss: 'Швейцарка',
            groups: 'Групи (Кругова)',
            supermele: 'Супермеле',
            teams: 'Команди',
            games: 'Поточні ігри',
            results: 'Результати',
            ranking: 'Таблиця',
            tournamentId: 'Id турніру',
            importPortal: 'Імпортувати з порталу',
            teamTitle: 'Назва команди',
            addTeam: 'Додати',
            addTeamMessage: 'додайте першу команду...',
            useTeamRating: 'Використовувати рейтинг під час жеребкування',
            removeTournament: 'Видалити турнір',
            saveTournament: 'Зберегти турнір',
            finishTournament: 'Закінчити турнір',
            preferences: 'Налаштування турніру',
            currentList: 'Список команд',
            rating: 'Рейтинг',
            playersInTeam: 'Скільки гравців у команді?',
            teamsInGroup: 'Скільки команд у групі?',
            protocol: 'протокол',
            copyProtocol: 'Скопіювати протокол',
            exportPdf: 'Експортувати в PDF',
            restoreTeams: 'Відновити останні команди',
        },
        remote: {
            remoteAvailabilities: 'Можливості для віддаленого керування',
            sendNotification: 'Надіслати сповіщення про оновлення турніру',
            showLinks: 'Показати посилання на турнір',
            writeMessage: 'Написати повідомлення',
            hideMessage: 'Сховати повідомлення',
            copyLink: 'Скопіювати посилання',
            qrAndLink: 'QR код та посилання на турнір',
        },
        games: {
            draw: 'Жеребкувати',
            first: 'Перший',
            shuffleLanes: 'Перемішати доріжки',
            show: 'Показати',
            compact: 'компактний',
            full: 'повний',
            view: 'вигляд',
            lane: 'Доріжка',
            saveResults: 'Зберегти результати',
            resultsError: 'Якась помилка у внесених результатах',
            restoreRound: 'Відновити попередній раунд',
            noGames: 'Поки що ігор немає',
            quantityError: 'Кількість раундів не може бути більшою за кількість команд',
            drawError: 'Сталася непередбачувана помилка при жеребкуванні. Дуже шкода. Ви можете написати розробнику про це (контакт внизу сторінки), але конкретно в цій ситуації це вам не допоможе:))',
            clickToDraw: 'Натисніть кнопку, щоб пожеребкувати',
            thirdPlace: 'Гра за 3 місце',
            final: 'Фінал',
            ofFinal: 'фіналу',
            tournamentFinished: 'Турнір завершено',
            seeResult: 'Подивитися результати',
            showBracket: 'Показати сітку плей-офф',
            playOff: 'Плей офф',
            someone: 'Якийсь',
            lucky: 'щасливчик',
            chooseSystem: 'Виберіть систему розіграшу',
            chooseSystemText: 'Забороняється грати турнір по швейцарській системі при кількості команд менше 8',
        },
        results: {
            title: 'Результати кожного раунду',
        },
        ranking: {
            ranking: 'Таблиця',
            after: 'після',
            round: 'раунду',
            swiss: 'швейцарки',
            rounds: 'раундів',
            noRanking: 'Ще нема результатів',
            points: 'Очки',
            pointsMobile: 'О',
            wins: 'Перемоги',
            winsMobile: 'П',
            team: 'Команда',
            place: 'Місце',
            rating: 'Рейтинг',
            ratingMobile: 'Р',
            difference: 'Різниця очок',
            differenceMobile: 'РО',
            player: 'Гравець',
            players: 'Гравці',
            sbuh: 'Малий бухгольць',
            sbuhMobile: 'МБ',
            buh: 'Коеф. бухгольця',
            buhMobile: 'Б',
            tournamentResult: 'Результати турніру',
            copyResults: 'Скопіювати результати',
            goPlayOff: 'Зіграємо на виліт?',
            chooseNumberTeams: 'Оберіть скільки команд зіграє плей-офф',
            go: 'Погнали!',
            alsoPlay: 'Також зіграємо',
            tournamentB: 'Турнір Б',
        },
        login: {
            back: 'Повернутися',
            email: 'Введіть електронну адресу',
            emailError: 'Адреса не корректна',
            password: 'Введіть пароль',
            passwordError: 'Пароль не вірний',
            forgot: 'Забули пароль? Оновіть його',
            registerAccount: 'Зареєструвати нового користувача',
            register: 'Зареєструватися',
            justLogin: 'Я вже зареєстрований',
            newUser: 'Новий користувач? Зареєструватися можна тут',
        },
        modals: {
            sureRemove: 'Ви впевнені, що хочете видалити турнір',
            tournamentName: 'Назва турніру',
            enterTournamentName: 'Введіть нову назву турніру',
            alreadyHaveName: 'Здається вже є турнір з такою назвою',
            resultsInTable: 'Результати в таблицях',
            tournamentPreferences: 'Налаштування турніру',
            maxScore: 'Максимально можливий рахунок',
            technicalScore: 'Рахунок для технічної перемоги',
        },
        common: {
            group: 'Група',
            change: 'Змінити',
            cancel: 'Відмінити',
            save: 'Зберегти',
            remove: 'Видалити',
            close: 'Зачинити',
            menu: 'Меню',
            activeTournaments: 'Активні турніри',
            loginAdmin: 'Увійти як адміністратор',
            loginUser: 'Увійти як користувач',
            logoutAdmin: 'Вийти як адміністратор',
            logoutUser: 'Вийти як користувач',
            language: 'Мова',
            please: 'Будь ласка,',
            round: 'Раунд',
            developedBy: 'Розроблено',
            onlyLoginMessage: 'Ви можете використовувати цю програму тільки коли увійдете в систему як користувач',
            addTournament: 'Додати новий турнір',
            adminSection: 'Авторизація',
            useful: 'Корисні посилання',
            info: 'Інформація',
            saved: 'Збережені турніри',
            choose: 'Виберіть',
            swissSystem: 'Про швейцарську систему',
            howUse: 'Як використовувати цю програму',
            portal: 'Портал ФПУ',
            show: 'Показати',
            hide: 'Cховати',
            games: 'Ігри',
            thankMe: 'Якщо вам подобається користуватися цією програмкою, можете подякувати мені тут',
            draw: 'Жеребкування',
            stat: 'Статистика',
            training: 'Тренування'
        },
        help: {
            title: 'Програма для жеребкування турнірів з петанку',
            description: 'Ця програма полегшить життя петанкістам, які організовують турніри, вболівають за улюблену команду або беруть участь у змаганнях. Для жеребкування вам знадобиться тільки інтернет. Гравцям більше не потрібно стояти біля столика організатора, щоб дізнатися, на якому майданчику та проти кого вони грають, чи знайти себе в турнірній таблиці. Тепер є можливість просто перейти з телефона за посиланням і все перевірити онлайн.',
            feature1: 'Програма жеребкує за швейцарською, круговою, олімпійською системах та супермеле.',
            feature2: 'Мінімум налаштувань.',
            feature3: 'Простий інтерфейс (ну так мені здається).',
            feature4: 'Можливість віддалено переглядати поточний статус турніру.',
            feature5: 'Чіткий алгоритм жеребкування за швейцарською системою. Програма не жеребкує команди рандомно. В цій версії, наприклад, якщо перші 6 команд мають однакову кількість перемог, то в наступному раунді вони зіграють за схемою: 1-6, 2-5, 3-4.',
            howToUseTitle: 'Як користуватися цією програмою',
            howToUse1: 'Для того щоб використовувати програму, треба зареєструвати акаунт. Жодних персональних даних, крім email, не потрібно (та й його ніхто не побачить, навіть я, розробник).',
            howToUse2: 'Користувач може використовувати програму як адміністратор (тільки для українських користувачів). Це дає змогу імпортувати гравців з порталу Федерації петанку України. Пароль я можу видати особисто за запитом.',
            shortTitle: 'Розділ для тих, кому не цікаві деталі',
            shortText: 'Щоб провести стандартний турнір за швейцарською системою + плей-офф, потрібно:',
            shortText1: 'Залогінитись як користувач.',
            shortText2: 'Додати назви команд на вкладці "Команди".',
            shortText3: 'Перейти на вкладку "Поточні ігри", пожеребкувати перший раунд.',
            shortText4: 'Внести результати, зберегти їх.',
            shortText5: 'Пожеребкувати наступні раунди, стільки, скільки ви хочете зіграти.',
            shortText6: 'Перейти на вкладку "Таблиця". Подивитись результати (якщо цікаво).',
            shortText7: 'Вибрати кількість команд, яка гратиме у плей-офф, і натиснути кнопку "Погнали".',
            shortText8: 'На вкладці "Поточні ігри" знову ввести всі результати.',
            shortText9: 'Коли ви внесете результати фіналу, турнір буде завершено. Його можна зберегти у себе в акаунті для історії або видалити з поточних турнірів.',
            shortSummary: 'Далі можна читати тим, кому цікаві "деталі".',
            interfaceTitle: 'Основний інтерфейс',
            interface1: 'Натиснувши на заголовок, можна змінити назву турніру.',
            interface2: 'Вибір системи, за якою буде проводитись турнір.',
            interface3: 'Тільки для адміністраторів: можливість імпортувати команди з порталу ФПУ. Для цього потрібно ввести останні цифри з URL-адреси турніру на порталі (наприклад, ',
            interface4: 'Назва команди (наприклад, прізвище капітана), яка буде додана в список команд після натискання "Додати".',
            interface5: 'Налаштування, чи слід використовувати рейтинг при жеребкуванні першого раунду.',
            tournamentControlsTitle: 'Керування турніром',
            tournamentControls1: 'Базові опції - налаштування турніру, можливість його зберегти, завершити або видалити.',
            tournamentControls2: 'Зберегти турнір можна тільки тоді, коли він завершений. Завершеним турнір вважається, коли внесені результати фіналу або натиснута кнопка "Завершити турнір".',
            tournamentControls3: 'Кнопка "Відновити останні команди" корисна, якщо ви вже пожеребкували перший раунд змагань і зрозуміли, що забули додати якусь команду, або якусь команду треба видалити. Додайте новий турнір і натисніть цю кнопку. Команди з попереднього турніру стануть доступними. Про те, як створити новий турнір, читайте в останньому пункті цієї інструкції.',
            mainTabs: 'Основні розділи',
            mainTabs1: 'Список команд, можливість додати чи видалити команду (до того, як пожеребкували перший раунд або будь-коли, якщо грається супермеле).',
            mainTabs2: 'Поточне жеребкування і внесення результатів.',
            mainTabs3: 'Результати всіх зіграних ігор.',
            mainTabs4: 'Підсумкова таблиця після кожного раунду і результати всього турніру.',
            preferences: 'Ті самі "мінімум налаштувань"',
            preferences1: 'Ці налаштування зовсім необов\'язкові.',
            preferences2: 'Інколи потрібно змінити результат технічної перемоги. Можна зробити це тут.',
            preferences3: 'Це налаштування може бути корисним, якщо ви граєте, наприклад, турнір серед клубів, де можливий результат 31:0.',
            drawResults: 'Жеребкування і результати',
            drawResultsText: 'Це найважливіша кнопка. Вона генерує суперників на кожен наступний раунд. У програмі ви не задаєте кількість раундів, які треба зіграти. Теоретично ви не зможете пожеребкувати більше раундів, ніж кількість команд на турнірі. Але при швейцарській системі треба бути обережним, якщо ви проводите турнір при невеликій кількості команд, але з відносно великою кількістю раундів. В якийсь момент програма не зможе виконати всі умови швейцарки і не зведе пари команд. Це може статися, якщо ви захочете провести, умовно, 7 турів при кількості команд не більше 12 (або 5 турів при 8). Тож ретельно продумайте систему, коли проводите такі турніри.',
            drawResults1: 'Кнопка, щоб перетасувати доріжки. Програма не слідкує за тим, чи грала одна команда декілька ігор на одній і тій самій доріжці. Ця функція корисна при невеликій кількості команд (загалом розподілення доріжок рандомне, крім плей-офф).',
            drawResults2: 'Компактніше відображення списку поточних ігор. Доступне тільки на мобільних пристроях.',
            drawResults3: 'Дуже важлива кнопка! Якщо ви помилились при внесенні результату, то є можливість змінити попередній раунд. Кнопка з\'являється після того, як ви пожеребкували наступний раунд. Ви можете виправити ТІЛЬКИ попередній раунд.',
            ranking: 'Ранкінг',
            rankingSwiss1: 'Підсумкова таблиця при швейцарській системі визначається за такими критеріями:',
            rankingSwiss2: 'Кількість перемог.',
            rankingSwiss3: 'Коефіцієнт Бухгольця (сума перемог суперників).',
            rankingSwiss4: 'Коефіцієнт малого Бухгольця (сума бухгольців суперників).',
            rankingSwiss5: 'Різниця набраних/пропущених очок.',
            rankingSwiss6: 'Після кожного раунду можна почати грати турнір за олімпійською системою (на виліт). Оберіть кількість кращих команд, з яких буде згенерована сітка плей-офф.',
            rankingSwiss7: 'Якщо вибрати цю галочку, то автоматично згенерується новий турнір, в який додадуться команди, що не вийшли у плей-офф.',
            rankingRound1: 'Якщо турнір грається за круговою системою, то підсумкова таблиця формується за такими критеріями:',
            rankingRound2: 'Кількість перемог.',
            rankingRound3: 'Результат особистої зустрічі (якщо команди грали між собою).',
            rankingRound4: 'Загальна різниця очок в усіх іграх.',
            rankingRound5: 'Але якщо кількість перемог однакова у трьох чи більше команд, то місця між цими командами розподіляються таким чином:',
            rankingRound6: 'Кількість перемог тільки у групі з цими командами.',
            rankingRound7: 'Різниця очок у групі з цими командами.',
            rankingRound8: 'Загальна різниця очок в усіх іграх.',
            playOff: 'Плей-офф',
            playOffText: 'Якщо турнір грається за олімпійською системою, то на вкладці "Поточні ігри" є можливість подивитись сітку плей-офф. Програма дозволяє жеребкувати максимум 64 команди за олімпійською системою.',
            roundSystem: 'Кругова система',
            roundSystemText: 'Вибираючи кругову систему турніру, можна автоматично розбити команди на групи. Для цього треба вибрати кількість команд в групі (система автоматично округлить кількість груп). Якщо групи не плануються, то треба вибрати ту кількість команд, яка зареєстрована.',
            roundSystemText1: 'Я рекомендую грати турнір з групами, якщо вам виходить зробити кількість команд в групах однаковою.',
            remoteControl: 'Віддалене керування',
            remoteControl1: 'Одна із основних фіч програми (ідея належить Олександру Ковалю) - можливість будь-кому переглядати поточне жеребкування і результати. Потрібне тільки посилання на турнір.',
            remoteControl2: 'Відкрити згенероване посилання на турнір. Це посилання можна розіслати всім учасникам турніру чи вболівальникам.',
            remoteControl3: 'Можна написати повідомлення, яке бачитимуть всі, хто зайде за посиланням. Корисно вписати інформацію про систему розіграшу, таймінги турніру чи побажати всім успіху.',
            remoteView: 'Віддалений перегляд',
            remoteViewText: 'Перейшовши за згенерованим посиланням, можна побачити таку інформацію:',
            remoteView1: 'Повідомлення, написане організатором турніру.',
            remoteView2: 'Поточні ігри турніру.',
            remoteView3: 'Вкладка з усіма попередніми результатами.',
            remoteView4: 'Вкладка з підсумковою таблицею турніру.',
            finishedTournament: 'Завершений турнір',
            finishedTournament1: 'Після того, як турнір завершено, будуть згенеровані фінальні результати на вкладці "Таблиця".',
            finishedTournament2: 'Також ви зможете зберегти результати турніру. Вони будуть доступні в меню, поки ви їх звідти не видалите.',
            finishedTournament3: 'Натиснувши кнопку "Скопіювати результати", ви можете скопіювати результати турніру в текстовому вигляді та надіслати їх адміністратору порталу ФПУ чи поділитися ними у месенджері.',
            tournamentsControlsTitle: 'Керування турнірами',
            tournamentsControls1: 'Додати новий турнір до поточного списку змагань.',
            tournamentsControls2: 'Переключатися між турнірами можна тут (або в мобільному меню, якщо використовуєте мобільний телефон).',
            tournamentsControls3: 'Одночасно в роботі може бути не більше 10 турнірів, тому слід видаляти неактуальні змагання.',
            thanksMessage: 'Дякую за ваш час. Питання, зауваження та пропозиції можна надсилати на',
            thanksMessagePost: 'пошту',
            thanksMessageOr: 'або у',
            thanksMessageMessenger: 'месенджер',
            pressBtnSeeInterface: 'Натиснувши цю кнопку, ви побачите такий інтерфейс:',
        },
        stat: {
            archive: 'Архів',
            enterName: 'Введіть назву гри',
            mode: 'Режим',
            scenario: 'Сценарій',
            system: 'Система',
            team: 'Команда',
            add: 'Додати',
            classic: 'Класичний',
            fast: 'Швидкий',
            simple: 'Проста',
            french: 'Французьська (A, B, ...)',
            positive: 'Позитивний',
            negative: 'Негативний',
            asCouch: 'Як тренер',
            start: 'Старт',
            prev: 'Попередній',
            next: 'Наступний',
            newGame: 'Нова гра',
            finishGame: 'Завершити гру',
            removeMan: 'Видалити цей мен',
            score: 'Рахунок',
            man: 'Мен',
            back: 'Назад',
            analysis: 'аналіз',
            everyManRes: 'Результат кожного раунду',
            resBoules: 'Мен',
            winBoules: 'Мен',
            series: 'Серії',
            all: 'Всі',
            points: 'Поінти',
            tirs: 'Шути',
            howManyPoints: 'Вкажіть скільки очок взяла команда',
            onlyLogin: 'Ви можете рахувати статистику тільки як залогінений користувач',
            total: 'Всього',
            changePlayer: 'Замінити гравця',
            enterPlayerName: 'Введіть ім\'я гравця',
            nothingShow: 'Нічого немає',
            findPlayer: 'Знайти гравця',
            choosePeriod: 'Вибрати період',
            chooseOnly: 'Показати тільки для ',
            clear: 'Очистити',
            noStat: 'Немає статистики для таких фільтрів',
        },
        training: {
            addEx: 'Додати вправу',
            exList: 'Список вправ',
            toList: 'Назад до списку',
            serieLength: 'кількість серій',
            distances: 'дистанції',
            asLogin: 'Ви можете рахувати тренувальну статистику тільки як зареєстрований користувач',
            addExToBegin: 'Додайте вправи, щоб почати тренування',
            viewResults: 'Подивитись результати',
            startTraining: 'Почати тренування',
            enterExName: 'Введіть назву вправи',
            serieQuantity: 'Кількість кидків у вправі на кожну дистанцію',
            nameSerie: 'Назвати кожну серію?',
            throwValue: '"Ціна" кидка',
            logical: 'Логічна (влучив / не влучив)',
            exScenario: 'Сценарій вправи',
            distFirst: 'Спочатку кидки по дистанціям',
            finishTraining: 'Закінчити тренування',
            attempt: 'кидок',
            meters: 'метрів',
            noResults: 'Поки немає результатів',
            points: 'Очки',
            distance: 'дистанція',
            exGradedText: 'Ця вправа оцінюється по набраним очкам, а не по відсоткам',
        }
    }
}