export default {
    en: {
        teams: {
            system: 'System',
            swiss: 'Swiss',
            groups: 'Groups (Round)',
            supermele: 'Supermele',
            teams: 'Teams',
            games: 'Current games',
            results: 'Results',
            ranking: 'Ranking',
            tournamentId: 'Tournament Id',
            importPortal: 'Import from portal',
            teamTitle: 'Team title',
            addTeam: 'Add team',
            addTeamMessage: 'add first team...',
            useTeamRating: 'Use team rating for drawing',
            removeTournament: 'Remove tournament',
            alreadyArchived: 'Tournament is already archived',
            saveTournament: 'Archive tournament',
            startTournament: 'Start tournament',
            saveTournamentData: 'Save data',
            finishTournament: 'Finish tournament',
            finishTournamentConfirm: 'Are you sure you want to finish the tournament?',
            preferences: 'Preferences',
            rating: 'Rating',
            playersInTeam: 'How many players in a team?',
            teamsInGroup: 'How many team in group?',
            protocol: 'protocol',
            copyProtocol: 'Copy protocol',
            exportPdf: 'Export to PDF',
            restoreTeams: 'Restore last teams',
        },
        games: {
            technical: 'Technical',
            draw: 'Draw',
            first: 'First',
            shuffleLanes: 'Shuffle lanes',
            show: 'Show',
            compact: 'compact',
            full: 'full',
            view: 'view',
            lane: 'Lane',
            lanesPlayed: 'lanes',
            saveResults: 'Save results',
            enterAllScores: 'Enter all scores first',
            resultsError: 'Some results are missing or incorrect',
            restoreRound: 'Restore previous round',
            restoreRoundConfirm: 'Are you sure you want to restore the previous round? This action cannot be undone.',
            noGames: 'No games, yet',
            quantityError: 'Rounds quantity can\'t be more than teams',
            drawError: 'There was an unexpectable error, sorry for that, you can write developer about it (contact in footer), but this will not help you in this situation:))',
            clickToDraw: 'Please, click on button to draw',
            thirdPlace: '3rd place',
            final: 'Final',
            ofFinal: 'final',
            tournamentFinished: 'Tournament has finished',
            seeResult: 'See result',
            showBracket: 'Show playoff bracket',
            playOff: 'PlayOff',
            cadrage: 'Cadrage',
            someone: 'Someone',
            lucky: 'Lucky guy',
            chooseSystem: 'Choose tournament system',
            chooseSystemText: 'Prohibited to play swiss system with less then 8 teams',
            playMaximum: 'You can play maximum ',
        },
        results: {
            title: 'Every round results',
            all: 'All',
        },
        ranking: {
            ranking: 'Ranking',
            after: 'after',
            round: 'round',
            rounds: 'rounds',
            swiss: 'swiss',
            noRanking: 'No ranking',
            points: 'Points',
            pointsMobile: 'P',
            pointsTooltip: 'Points scored : points conceded',
            wins: 'Wins',
            winsMobile: 'W',
            team: 'Team',
            place: 'Place',
            rating: 'Rating',
            ratingMobile: 'R',
            difference: 'Difference',
            differenceMobile: 'D',
            player: 'Player',
            players: 'Players',
            sbuh: 'SBuh',
            sbuhMobile: 'S',
            sbuhTooltip: 'Sum of Buchholz scores of all opponents',
            buh: 'Buh',
            buhMobile: 'B',
            buhTooltip: 'Sum of wins of all opponents',
            roundsPlayed: 'Rounds played',
            tournamentResult: 'Tournament Result',
            swissTable: 'Swiss table',
            copyResults: 'Copy results',
            goPlayOff: 'Go to play-off?',
            withCadrage: 'With cadrage',
            cadrageHint: 'Extra round for teams on the edge of the playoff zone to compete for a spot',
            doubleElimination: 'Double elimination',
            doubleEliminationHint: 'Teams must lose twice to be eliminated. Losers from the winner bracket get a second chance in the loser bracket.',
            doubleEliminationAlt: 'Split teams between brackets',
            doubleEliminationAltHint: 'Top teams go to winner bracket, bottom teams start in loser bracket',
            winnerBracket: 'Winner bracket',
            loserBracket: 'Loser bracket',
            grandFinal: 'Grand Final',
            loserBracketTeams: 'Teams in loser bracket',
            chooseNumberTeams: 'Choose number of teams',
            go: 'Go!',
            alsoPlay: 'Also play',
            tournamentB: 'Tournament B',
        },
        remote: {
            remoteAvailabilities: 'Remote availabilities',
            sendNotification: 'Send update notification',
            showLinks: 'Show tournament links',
            showLink: 'Show link',
            writeMessage: 'Write a message',
            hideMessage: 'Hide the message',
            messageSaved: 'Message saved',
            organizerMessage: 'Organizer',
            copyLink: 'Copy link',
            linkCopied: 'Link copied to clipboard',
            qrAndLink: 'QR code and link for tournament',
        },
        login: {
            back: 'Back',
            email: 'Enter email',
            emailPlaceholder: 'Email',
            emailError: 'Email is not correct',
            password: 'Enter password',
            passwordPlaceholder: 'Password',
            confirmPlaceholder: 'Confirm password',
            passwordError: 'Password is not correct',
            forgot: 'Forgot password?',
            forgotHint: 'Enter your email and we\'ll send you a reset link',
            resetPassword: 'Send reset link',
            backToLogin: 'Back to login',
            loginTitle: 'Welcome back',
            loginBtn: 'Sign in',
            registerTitle: 'Create account',
            register: 'Sign up',
            justLogin: 'Sign in',
            noAccount: 'Don\'t have an account?',
            hasAccount: 'Already have an account?',
            newUser: 'New User? Register here',
            registerAccount: 'Register new account',
        },
        modals: {
            sureRemove: 'Are you sure you want to delete',
            tournamentName: 'Tournament name',
            enterTournamentName: 'Please, enter tournament name',
            tournamentNameRequired: 'Tournament name cannot be empty',
            alreadyHaveName: 'It seems you already have such tournament name',
            resultsInTable: 'Results in tables',
            tournamentPreferences: 'Tournament preferences',
            maxScore: 'Maximum score',
            technicalScore: 'Technical score',
            technicalScoreHint: 'Score awarded for a technical win (walkover)',
            maxScoreHint: 'Game ends when a team reaches this score',
            playOffTeams: 'How many team go to playoff?',
            playOffTeamsHint: 'Number of top teams advancing to the knockout stage',
            playOffAlreadyStarted: 'Cannot change — playoff has already started',
            fieldsStart: 'From which field should the numbering begin?',
            fieldsStartHint: 'First lane number (useful if your venue lanes start from a different number)',
            removeHint: 'This action cannot be undone',
        },
        setup: {
            readyToStart: 'Tournament setup',
            drawFirstRound: 'Draw first round',
            enablePlayOff: 'Play-off after Swiss rounds',
            additionalSettings: 'Additional settings',
        },
        common: {
            updated: 'has updated!',
            swissCalculator: 'Swiss system calculator',
            group: 'Group',
            change: 'Change',
            cancel: 'Cancel',
            save: 'Save',
            remove: 'Remove',
            pin: 'Pin as default',
            unpin: 'Unpin',
            close: 'Close',
            menu: 'Menu',
            activeTournaments: 'Active tournaments',
            loginUser: 'Log in as User',
            logoutAdmin: 'Logout as Admin',
            logoutUser: 'Logout',
            language: 'Language',
            please: 'Please,',
            round: 'Round',
            or: 'or',
            developedBy: 'Developed by',
            onlyLoginMessage: 'You can use this program only when login to the system as User',
            addTournament: 'Add new tournament',
            adminSection: 'Authorisation',
            useful: 'Petanque apps',
            info: 'Info',
            settings: 'Settings',
            saved: 'Saved tournaments',
            archivedTournaments: 'Archived tournaments',
            choose: 'Choose',
            tournamentName: 'Tournament name',
            swissSystem: 'About Swiss System',
            howUse: 'How to use',
            portal: 'FPU Portal',
            show: 'Show',
            hide: 'Hide',
            games: 'Games',
            thankMe: 'If you like to use this program, you can thank me here',
            draw: 'Draw',
            stat: 'Statistics',
            training: 'Training',
            status: 'Status',
            active: 'Active',
            finished: 'Finished',
            notStarted: 'Not started',
            teamsCount: 'Teams',
            timeLimit: 'Time limit',
            places: 'places',
            teamsLabel: 'teams',
        },
        help: {
            title: 'Tournament Drawing App for Petanque',
            description: 'This app simplifies the lives of petanque players who organize tournaments, cheer for their favorite team, or participate in competitions. All you need for drawing is internet access. Players no longer need to gather around the organizer’s table to find out their playing field, opponents, or their position in the standings. Now, they can simply follow a link on their phone to check everything online.',
            feature1: 'The app supports Swiss, round-robin, knockout systems, and supermelee.',
            feature2: 'Minimal settings.',
            feature3: 'Simple interface (or so I believe).',
            feature4: 'Ability to remotely view the current tournament status.',
            feature5: 'Precise drawing algorithm for the Swiss system. The app doesn’t draw teams randomly. For example, if the top 6 teams have the same number of wins, in the next round they will play as follows: 1-6, 2-5, 3-4.',
            howToUseTitle: 'How to Use This App',
            howToUse1: 'To use the app, you need to register an account. No personal data other than email is required (and even that remains private, not even visible to me, the developer).',
            howToUse2: 'Users can use the app as administrators (available only for Ukrainian users). This allows importing players from the Ukrainian Federation portal. I can issue a password personally upon request.',
            shortTitle: 'Quick Start Guide',
            shortText: 'To conduct a standard Swiss system tournament + playoffs, you need to:',
            shortText1: 'Log in as a user.',
            shortText2: 'Add team names on the "Teams" tab.',
            shortText3: 'Go to the "Current Games" tab and draw the first round.',
            shortText4: 'Enter the results and save them.',
            shortText5: 'Draw subsequent rounds as many as you wish to play.',
            shortText6: 'Go to the "Standings" tab to check the results (if interested).',
            shortText7: 'Select the number of teams for the playoffs and click "Let’s Go".',
            shortText8: 'Enter all results again on the "Current Games" tab.',
            shortText9: 'Once you input the final results, the tournament is completed. You can save it in your account for history or remove it from current tournaments.',
            shortSummary: 'Continue reading for more details.',
            interfaceTitle: 'Main Interface',
            interface1: 'Click on the title to change the tournament name.',
            interface2: 'Select the system for the tournament.',
            interface3: 'Admins only: Import teams from the UFP portal. Enter the last digits from the portal’s tournament URL (e.g.,',
            interface4: 'Team name (e.g., captain’s last name) will be added to the team list upon clicking "Add team".',
            interface5: 'Option to use rankings for the first round draw.',
            tournamentControlsTitle: 'Tournament Management',
            tournamentControls1: 'Basic options: configure, save, complete, or delete the tournament.',
            tournamentControls2: 'You can only save a tournament once it’s completed. A tournament is completed when the final results are entered or the "Complete Tournament" button is clicked.',
            tournamentControls3: 'The "Restore Last Teams" button is helpful if you’ve drawn the first round and realize you forgot to add or need to remove a team. Create a new tournament and click this button. Teams from the previous tournament will be available. See the last section of this guide for details on creating a new tournament.',
            mainTabs: 'Main Sections',
            mainTabs1: 'Team list: add or remove teams (before drawing the first round or anytime for supermelee).',
            mainTabs2: 'Current draw and result entry.',
            mainTabs3: 'Results of all games played.',
            mainTabs4: 'Final standings after each round and the overall tournament results.',
            preferences: 'Those "Minimal Settings"',
            preferences1: 'These settings are entirely optional.',
            preferences2: 'Occasionally, you might need to adjust the result of a technical victory. You can do this here.',
            preferences3: 'This setting can be useful for club tournaments, where a score of 31:0 is possible.',
            drawResults: 'Draw and Results',
            drawResultsText: 'This is the most important button. It generates opponents for each subsequent round. The app doesn’t ask for the total number of rounds. You won’t be able to draw more rounds than the number of teams. However, in the Swiss system, be cautious with small team counts and many rounds. At some point, the app won’t be able to satisfy all Swiss system conditions and won’t pair teams. This could happen, for example, with 7 rounds and 12 teams or 5 rounds and 8 teams. Plan carefully when running such tournaments.',
            drawResults1: 'Button to shuffle lanes. The app doesn’t track if a team plays multiple games on the same lane. This is useful for small tournaments (lane assignments are random except in playoffs).',
            drawResults2: 'Compact view of current games, available only on mobile devices.',
            drawResults3: 'Key button! If you make a mistake entering results, you can edit the previous round. This button appears after the next round is drawn. You can restore ONLY previous round.',
            ranking: 'Ranking',
            rankingSwiss1: 'Standings for the Swiss system are determined by these criteria:',
            rankingSwiss2: 'Number of wins.',
            rankingSwiss3: 'Buchholz coefficient (sum of opponents’ wins).',
            rankingSwiss4: 'Minor Buchholz coefficient (sum of opponents’ Buchholz).',
            rankingSwiss5: 'Points difference (scored vs. conceded).',
            rankingSwiss6: 'After each round, you can switch to a knockout tournament. Choose the top teams to generate a playoff bracket.',
            rankingSwiss7: 'If this box is checked, a new tournament with non-playoff teams will be generated automatically.',
            rankingRound1: 'Standings for the round-robin system are determined by:',
            rankingRound2: 'Number of wins.',
            rankingRound3: 'Head-to-head result (if teams played each other).',
            rankingRound4: 'Overall point difference across all games.',
            rankingRound5: 'If three or more teams are tied, ranking is determined by:',
            rankingRound6: 'Wins within the group of tied teams.',
            rankingRound7: 'Point difference within the group of tied teams.',
            rankingRound8: 'Overall point difference across all games.',
            playOff: 'Playoffs',
            playOffText: 'For knockout tournaments, view the playoff bracket on the "Current Games" tab. The app supports up to 64 teams in a knockout bracket.',
            roundSystem: 'Round-Robin System',
            roundSystemText: 'For round-robin tournaments, you can automatically split teams into groups. Select the number of teams per group (the system rounds off the number of groups). If no groups are planned, select the total registered teams.',
            roundSystemText1: 'I recommend using groups only if you can have equal numbers of teams in each group.',
            remoteControl: 'Remote Control',
            remoteControl1: 'One of the key features of the app (idea by Oleksandr Koval) is the ability for anyone to view current draws and results. All they need is the tournament link.',
            remoteControl2: 'Open the generated tournament link. Share it with participants or fans.',
            remoteControl3: 'You can post a message visible to everyone who visits the link. Use it to share tournament details, timings, or well wishes.',
            remoteView: 'Remote Viewing',
            remoteViewText: 'With the generated link, viewers can see:',
            remoteView1: 'Message from the tournament organizer.',
            remoteView2: 'Current games.',
            remoteView3: 'All previous results.',
            remoteView4: 'Final standings.',
            finishedTournament: 'Completed Tournament',
            finishedTournament1: 'After the tournament is completed, final results will appear on the "Ranking" tab.',
            finishedTournament2: 'You can save the tournament results, which remain available in the menu until deleted.',
            finishedTournament3: 'Use the "Copy Results" button to copy tournament results in text format to share via messenger.',
            tournamentsControlsTitle: 'Tournament Management',
            tournamentsControls1: 'Add a new tournament to the current list.',
            tournamentsControls2: 'Switch between tournaments here (or in the mobile menu, if using phone).',
            tournamentsControls3: 'You can manage up to 10 tournaments simultaneously. Delete outdated ones as needed.',
            thanksMessage: 'Thank you for your time. Send questions, comments, and suggestions to',
            thanksMessagePost: 'email',
            thanksMessageOr: 'or',
            thanksMessageMessenger: 'messenger',
            pressBtnSeeInterface: 'Press this button to see the interface:',
            "training": {
                "title": "Training",
                "description": "This module is designed to track the training process. It allows you to create exercises for training, record, and analyze their results.",
                "exerciseListTitle": "Exercise List Page",
                "exerciseList": {
                    "add": "Go to the add new exercise page",
                    "list": "List of created exercises",
                    "delete": "Delete exercise",
                    "viewResults": "View all results of a specific exercise",
                    "startTraining": "Start training for a specific exercise"
                },
                "addExerciseTitle": "Add New Exercise Page",
                "addExerciseDescription": "Typically, any exercise consists of a certain number of throws at a certain number of distances. The combination of these options allows you to create any training exercise variation.",
                "addExercise": {
                    "back": "Return to exercise list",
                    "name": "Exercise name, as it will appear in the general list",
                    "distances": "Distances for which the exercise will be performed",
                    "throws": "Number of throws for each distance",
                    "series": "Here you can name each series. Thus, you can perform a comprehensive exercise. As an example – a shooting competition. In fact, you are performing three different exercises. Example of creation – at the end of the page.",
                    "scoring": "How each throw will be evaluated. You can choose a logical value (hit/miss, set/not set) or score each throw with a certain number of points.",
                    "scenario": "If you choose a logical value, the option to select a training scenario becomes available. If positive - all throws will be marked as successful by default, and vice versa.",
                    "order": "When there are multiple distances and a certain number of throws for each, you can conduct training in different sequences. First, throw a series of, for example, 10 throws at one distance, then 10 throws at the next, and so on. Or you can throw one throw at each distance in rotation."
                },
                "trainingProcessTitle": "Training Process Page",
                "trainingProcess": {
                    "inputResult": "Enter throw result here",
                    "navigation": "Navigation through throws or distances",
                    "finish": "When all throws are completed, to finish the training and calculate the result, press here"
                },
                "exerciseResultsTitle": "Exercise Results Page",
                "exerciseResults": {
                    "average": "The average result for the exercise over the entire history of records (can be either a percentage or a specific number, depending on the selected throw result value)",
                    "byDistance": "Results for each distance separately",
                    "history": "Results of each training session in chronological order"
                },
                exampleCreation: "Example of creating a classical shooting exercise",
                exampleCreationText: "With these settings, you will create an exercise for recording training results according to the rules of classical shooting."
            },
            "stat": {
                "title": "Statistics",
                "description": "Allows you to count statistics in pétanque games and analyze data according to various criteria.",
                "settings": {
                    "title": "Game Settings",
                    "description": "The main settings require only specifying the game name and the game format (triplet, doublet, or têt). It is also recommended to specify the players.",
                    "gameName": "The name of the game as it will appear in the list.",
                    "tags": "Game tags. These are keywords that can describe the game and allow future filtering of data. For example, you might want to know how you played in games of a specific tournament or analyze statistics for different fields. You can manage tags by clicking the \"Show tags\" button.",
                    "mode": "Mode. The fast mode was created to make it more comfortable to record statistics during the game as a player. It allows you to spend less time looking at your phone. More details below.",
                    "showStats": "If you check this box, the statistics will be displayed during the game. This allows decisions to be made regarding player substitutions. If you are recording statistics as a player, this could influence your decisions during the game.",
                    "scoringSystem": "Select a scoring system. Currently, you can use the simple or French system. At this stage, analysis is available only for the simple system.",
                    "scenario": "Game scenario. Here you can specify which throwing result will be shown by default. If you are playing as one of the top world players, use the positive scenario."
                },
                "tracking": {
                    "title": "Tracking",
                    "distance": "For each round, you can specify the distance players are playing. It is not mandatory, but it allows you to filter data by distance during analysis. This sets the distance for all throws in this round. If you want to change the distance for a specific throw, see point 7.",
                    "teamStats": "Current team statistics as percentages and overall (only displayed if \"Coach\" checkbox is selected).",
                    "playerStats": "Current player statistics (only displayed if \"Coach\" checkbox is selected).",
                    "shotsSeries": "Player's shot series (green - successful shot, red - unsuccessful shot, blue - caro (only in tie)).",
                    "roundPoints": "How many points the team won in the played round.",
                    "highlight": "A green exclamation mark shows a caro in a tie or point where 2 balls were played.",
                    "contextMenu": "Context menu for a throw. Appears when pressing the throw result for more than half a second. Additional shot effectiveness can be specified (for a successful shot, this means a caro, for a miss it means a knocked-out ball, for a point, it could mean either a knocked-out ball or a moved cochonnet with more than one ball played). You can also delete the throw (relevant for fast play mode when a cochonnet was knocked out and not all balls were thrown). Also, you can change the distance of a specific throw (relevant when the cochonnet was moved during the game).",
                    "shotType": "The type and result of the shot. This can be toggled with a simple press.",
                    "negativeHighlight": "A red exclamation mark indicates a knocked-out ball or a foreign ball played after the throw.",
                    "navigation": "Navigation between rounds."
                },
                "result": {
                    "title": "Game Result",
                    "finalScore": "Game result.",
                    "teamPerformance": "Final team performance.",
                    "shotsPerRound": "Successful shots per round (accurate only when you specify the successful shot as one that \"played\"). This is a rather specific metric that may not be useful for everyone.",
                    "roundPoints": "How many points the team won in each round.",
                    "playerSeries": "Series of throws for each player.",
                    "playerPerformance": "Individual player performance by the end of the game."
                },
                "modes": {
                    "title": "Modes and Scenarios",
                    "simple": "Simple mode. The first click makes the throw active. This is counted as a performed throw.",
                    "fastModePositive": "Fast mode. At the beginning of the round, all throws are recorded as performed. Below is fast mode with a POSITIVE scenario. By default, all throws are successful.",
                    "fastModeNegative": "Here is the NEGATIVE scenario. Currently, this scenario is winning in Ukraine.",
                    "fastModeDescription": "Fast mode allows you to track statistics without being distracted by recording EVERY throw. It was made to make it easier to enter data during the game."
                },
                "tags": {
                    "title": "Tags",
                    "description": "Tags are keywords that describe games. You can create and delete tags.",
                    "usage": "For each game, you can add an unlimited number of tags (this can be done either at the start of the game or later when the game is already recorded). This allows you to filter games by these tags and analyze statistics accordingly. For example, you could add the tag 'Hard Court' and then look at statistics only on hard courts. The possibilities are endless."
                },
                "substitutions": {
                    "title": "Substitutions",
                    "description": "During the game, you can make a player substitution. Hover over the player's name, and a button will appear that opens a modal window where you can enter the new player's name."
                },
                "archive": {
                    "title": "Archive",
                    "description": "This page stores all recorded games.",
                    "filterTags": "Tags that can be used to filter games.",
                    "gameName": "Game name. You can delete the game, but you cannot change its name.",
                    "recordDate": "Date when the game was recorded.",
                    "addedTags": "Tags added to the game.",
                    "addTag": "Option to add a new tag to the game after it has been recorded."
                },
                "analysis": {
                    "title": "Analysis",
                    "description": "In this section, you can view detailed statistics for a specific player.",
                    "selectPlayer": "Select a player to view their statistics.",
                    "selectPeriod": "Select the period for which statistics will be displayed.",
                    "selectFormat": "Select the game format for the statistics.",
                    "selectTag": "Select the tag to filter the statistics.",
                    "selectDistance": "Select the distance for which statistics will be displayed.",
                    "result": "The result based on the selected filters.",
                    "charts": "Charts showing the dynamics of statistics, separately for points and shots."
                }
            }
        },
        stat: {
            archive: 'Archive',
            enterName: 'Enter game name',
            mode: 'Mode',
            scenario: 'Scenario',
            system: 'System',
            format: 'Format',
            team: 'Team',
            add: 'Add',
            classic: 'Classic',
            fast: 'Fast',
            simple: 'Simple',
            french: 'French (A, B, ...)',
            positive: 'Positive',
            negative: 'Negative',
            asCoach: 'As coach',
            start: 'Start',
            prev: 'Prev',
            next: 'Next',
            newGame: 'New game',
            finishGame: 'Finish game',
            removeMan: 'Remove this round',
            score: 'Score',
            man: 'Round',
            back: 'Back',
            analysis: 'analysis',
            everyManRes: 'Every round result',
            resBoules: 'Round',
            winBoules: 'Round',
            series: 'Series',
            all: 'All',
            points: 'Points',
            tirs: 'Tirs',
            howManyPoints: 'Enter how many points team won',
            onlyLogin: 'You can count statistic only as login user',
            total: 'Total',
            changePlayer: 'Change player',
            enterPlayerName: 'Enter player name',
            nothingShow: 'Nothing to show',
            findPlayer: 'Find Player',
            choosePeriod: 'Choose period',
            chooseOnly: 'Choose only',
            clear: 'Clear',
            noStat: 'No statistics with your filters',
            whatDistance: 'What distance?',
            important: 'Important throws',
            games: 'games',
            gameTags: 'Game tags',
            addTag: 'Add tag',
            showTags: 'Show',
            hideTags: 'Hide',
            tags: 'tags',
            playerName: 'Player',
            team1Label: 'Team 1',
            team2Label: 'Team 2',
        },
        messages: {
            sent: 'Sent!',
            checkEmail: 'Check your email',
            error: 'Error',
            somethingWrong: 'Something went wrong',
            missingEmail: 'Missing email',
            invalidEmail: 'Invalid email',
            noAccount: 'No account with this email',
            incorrectPassword: 'Incorrect password',
            passwordMismatch: 'Passwords do not match',
            weakPassword: 'Password must be at least 6 characters',
            cantDraw: 'Can\'t draw',
            someError: 'Some error happened',
            cantDrawRound: 'Can\'t draw this round',
            tooManyGames: 'Too many games for swiss with this number of teams',
            chooseCorrectTeams: 'Choose correct number of teams in group',
            success: 'Success',
            resultsSaved: 'Your results saved',
            teamExists: 'Such team already registered! Change team title, please',
            enterFields: 'Enter fields to add team',
            awesome: 'Awesome!',
            statsSaved: 'Statistics saved',
            failedLoadTags: 'Failed to load tags',
            exercisesLoaded: 'Exercises successfully loaded',
            noExercisesFound: 'No exercises found for you',
            info: 'Info',
            failedLoadData: 'Failed to load data',
            exerciseRemoved: 'Exercise successfully removed',
            notAllResults: 'Not all results',
            someAttemptsNotWritten: 'Some attempts not written',
            youAreOffline: 'You are offline',
            trainingSavedBrowser: 'Your training saved in browser. Save it when you will be online',
            exerciseSaved: 'Exercise saved',
            protocolCopied: 'Protocol is in your buffer',
            cantCopyProtocol: 'Can\'t copy protocol',
            tagSaved: 'Tag saved',
            tagUpdated: 'Tag updated',
            removed: 'Removed',
            tournamentRemoved: 'Tournament has been removed',
            notAvailable: 'Not available',
            maxTournaments: 'You can make only 10 tournaments. Remove one to add new',
            saved: 'Saved',
            tournamentSavedList: 'You can see your saved tournaments in the menu',
            tournamentRemovedSaved: 'Tournament removed from your saved list',
            tournamentDataSaved: 'Tournament data saved',
            failedSaving: 'Something went wrong while saving',
            removeExercise: 'Remove this exercise?',
            tournamentNotActive: 'Tournament is not active',
            noArchivedTournaments: 'Your archived tournaments will appear here after you finish and save them',
            gameRemoved: 'Game successfully removed',
            tagRemoved: 'Tag successfully removed',
            failedSaveData: 'Failed to save data',
            tournamentPinned: 'This tournament will open by default',
            tournamentUnpinned: 'Tournament unpinned',
            preferencesSaved: 'Settings saved',
        },
        training: {
            addEx: 'Add exercise',
            exList: 'Exercises list',
            toList: 'To list',
            serieLength: 'serie length',
            distances: 'distances',
            asLogin: 'You can count trainings statistic only as login user',
            addExToBegin: 'Add exercise to begin trainings',
            viewResults: 'View results',
            startTraining: 'Start training',
            enterExName: 'Enter training exercise name',
            serieQuantity: 'Serie quantity',
            nameSerie: 'Name every serie?',
            throwValue: 'Throw value',
            logical: 'Logical',
            exScenario: 'Exercise scenario',
            distFirst: 'Distance first',
            finishTraining: 'Finish training',
            attempt: 'attempt',
            meters: 'meters',
            noResults: 'No results',
            distance: 'Distance',
            exGradedText: 'This exercise is graded by points scored, not percentages',
            average: 'All time Average result ',
            points: 'Points ',
        }
    },
    ua: {
        teams: {
            system: 'Система',
            swiss: 'Швейцарка',
            groups: 'Групи (Кругова)',
            supermele: 'Супермеле',
            teams: 'Команди',
            games: 'Поточні ігри',
            results: 'Результати',
            ranking: 'Таблиця',
            tournamentId: 'Id турніру',
            importPortal: 'Імпортувати з порталу',
            teamTitle: 'Назва команди',
            addTeam: 'Додати',
            addTeamMessage: 'додайте першу команду...',
            useTeamRating: 'Використовувати рейтинг під час жеребкування',
            removeTournament: 'Видалити турнір',
            alreadyArchived: 'Турнір вже архівовано',
            saveTournament: 'Архівувати турнір',
            startTournament: 'Старт',
            saveTournamentData: 'Зберегти дані',
            finishTournament: 'Закінчити турнір',
            finishTournamentConfirm: 'Ви впевнені, що хочете закінчити турнір?',
            preferences: 'Налаштування турніру',
            rating: 'Рейтинг',
            playersInTeam: 'Скільки гравців у команді?',
            teamsInGroup: 'Скільки команд у групі?',
            protocol: 'протокол',
            copyProtocol: 'Скопіювати протокол',
            exportPdf: 'Експортувати в PDF',
            restoreTeams: 'Відновити останні команди',
        },
        remote: {
            remoteAvailabilities: 'Можливості для віддаленого керування',
            sendNotification: 'Надіслати сповіщення про оновлення турніру',
            showLinks: 'Показати посилання на турнір',
            showLink: 'Посилання',
            writeMessage: 'Написати повідомлення',
            hideMessage: 'Сховати повідомлення',
            messageSaved: 'Повідомлення збережено',
            organizerMessage: 'Організатор',
            copyLink: 'Скопіювати посилання',
            linkCopied: 'Посилання скопійовано',
            qrAndLink: 'QR код та посилання на турнір',
        },
        games: {
            technical: 'Технічна',
            draw: 'Жеребкувати',
            first: 'Перший',
            shuffleLanes: 'Перемішати доріжки',
            show: 'Показати',
            compact: 'компактний',
            full: 'повний',
            view: 'вигляд',
            lane: 'Доріжка',
            lanesPlayed: 'доріжки',
            saveResults: 'Зберегти результати',
            enterAllScores: 'Спочатку введіть всі результати',
            resultsError: 'Не всі результати заповнені або містять помилки',
            restoreRound: 'Відновити попередній раунд',
            restoreRoundConfirm: 'Ви впевнені, що хочете відновити попередній раунд? Цю дію неможливо скасувати.',
            noGames: 'Поки що ігор немає',
            quantityError: 'Кількість раундів не може бути більшою за кількість команд',
            drawError: 'Сталася непередбачувана помилка при жеребкуванні. Дуже шкода. Ви можете написати розробнику про це (контакт внизу сторінки), але конкретно в цій ситуації це вам не допоможе:))',
            clickToDraw: 'Натисніть кнопку, щоб пожеребкувати',
            thirdPlace: '3 місце',
            final: 'Фінал',
            ofFinal: 'фіналу',
            tournamentFinished: 'Турнір завершено',
            seeResult: 'Подивитися результати',
            showBracket: 'Показати сітку плей-офф',
            playOff: 'Плей офф',
            cadrage: 'Кадраж',
            someone: 'Якийсь',
            lucky: 'щасливчик',
            chooseSystem: 'Виберіть систему розіграшу',
            chooseSystemText: 'Забороняється грати турнір по швейцарській системі при кількості команд менше 8',
            playMaximum: 'Ви можете зіграти максимум',
        },
        results: {
            title: 'Результати кожного раунду',
            all: 'Всі',
        },
        ranking: {
            ranking: 'Таблиця',
            after: 'після',
            round: 'раунду',
            swiss: 'швейцарки',
            rounds: 'раундів',
            noRanking: 'Ще нема результатів',
            points: 'Очки',
            pointsMobile: 'О',
            pointsTooltip: 'Набрані очки : пропущені очки',
            wins: 'Перемоги',
            winsMobile: 'П',
            team: 'Команда',
            place: 'Місце',
            rating: 'Рейтинг',
            ratingMobile: 'Р',
            difference: 'Різниця очок',
            differenceMobile: 'РО',
            player: 'Гравець',
            players: 'Гравці',
            sbuh: 'Малий бухгольць',
            sbuhMobile: 'МБ',
            sbuhTooltip: 'Сума бухгольців усіх суперників',
            buh: 'Коеф. бухгольця',
            buhMobile: 'Б',
            buhTooltip: 'Сума перемог усіх суперників',
            roundsPlayed: 'Зіграно раундів',
            tournamentResult: 'Результати турніру',
            swissTable: 'Таблиця швейцарки',
            copyResults: 'Скопіювати результати',
            goPlayOff: 'Зіграємо на виліт?',
            withCadrage: 'З кадражем',
            cadrageHint: 'Додатковий раунд для команд на межі плей-офф зони, щоб розіграти місце',
            doubleElimination: 'Подвійне вибування',
            doubleEliminationHint: 'Команди мають програти двічі, щоб вибути. Переможені у верхній сітці отримують другий шанс у нижній.',
            doubleEliminationAlt: 'Розділити команди між сітками',
            doubleEliminationAltHint: 'Найкращі команди йдуть у верхню сітку, решта стартують у нижній',
            winnerBracket: 'Верхня сітка',
            loserBracket: 'Нижня сітка',
            grandFinal: 'Гранд-фінал',
            loserBracketTeams: 'Команди у нижній сітці',
            chooseNumberTeams: 'Оберіть скільки команд зіграє плей-офф',
            go: 'Погнали!',
            alsoPlay: 'Також зіграємо',
            tournamentB: 'Турнір Б',
        },
        login: {
            back: 'Повернутися',
            email: 'Введіть електронну адресу',
            emailPlaceholder: 'Email',
            emailError: 'Адреса не корректна',
            password: 'Введіть пароль',
            passwordPlaceholder: 'Пароль',
            confirmPlaceholder: 'Підтвердьте пароль',
            passwordError: 'Пароль не вірний',
            forgot: 'Забули пароль?',
            forgotHint: 'Введіть email і ми надішлемо посилання для скидання',
            resetPassword: 'Надіслати посилання',
            backToLogin: 'Повернутися до входу',
            loginTitle: 'Вхід',
            loginBtn: 'Увійти',
            registerTitle: 'Створити акаунт',
            register: 'Зареєструватися',
            justLogin: 'Увійти',
            noAccount: 'Немає акаунту?',
            hasAccount: 'Вже є акаунт?',
            newUser: 'Новий користувач? Зареєструватися можна тут',
            registerAccount: 'Зареєструвати нового користувача',
        },
        modals: {
            sureRemove: 'Ви впевнені, що хочете видалити турнір',
            tournamentName: 'Назва турніру',
            enterTournamentName: 'Введіть нову назву турніру',
            tournamentNameRequired: 'Назва турніру не може бути порожньою',
            alreadyHaveName: 'Здається вже є турнір з такою назвою',
            resultsInTable: 'Результати в таблицях',
            tournamentPreferences: 'Налаштування турніру',
            maxScore: 'Максимально можливий рахунок',
            technicalScore: 'Рахунок для технічної перемоги',
            technicalScoreHint: 'Рахунок, який присвоюється за технічну перемогу (неявка)',
            maxScoreHint: 'Гра завершується, коли команда досягає цього рахунку',
            playOffTeams: 'Скільки команд виходять у плей-офф?',
            playOffTeamsHint: 'Кількість найкращих команд, які проходять у етап на виліт',
            playOffAlreadyStarted: 'Неможливо змінити — плей-офф вже розпочато',
            fieldsStart: 'З якого майданчика починати нумерацію?',
            fieldsStartHint: 'Перший номер майданчика (корисно, якщо нумерація на вашому місці починається з іншого числа)',
            removeHint: 'Цю дію неможливо скасувати',
        },
        setup: {
            readyToStart: 'Налаштування турніру',
            drawFirstRound: 'Жеребкувати перший раунд',
            enablePlayOff: 'Плей-офф після швейцарських раундів',
            additionalSettings: 'Додаткові налаштування',
        },
        common: {
            updated: 'оновлено!',
            swissCalculator: 'Калькулятор швейцарки',
            group: 'Група',
            change: 'Змінити',
            cancel: 'Відмінити',
            save: 'Зберегти',
            pin: 'Закріпити',
            unpin: 'Відкріпити',
            remove: 'Видалити',
            close: 'Зачинити',
            menu: 'Меню',
            activeTournaments: 'Активні турніри',
            loginUser: 'Увійти як користувач',
            logoutAdmin: 'Вийти як адміністратор',
            logoutUser: 'Вийти',
            language: 'Мова',
            please: 'Будь ласка,',
            round: 'Раунд',
            or: 'або',
            developedBy: 'Розроблено',
            onlyLoginMessage: 'Ви можете використовувати цю програму тільки коли увійдете в систему як користувач',
            addTournament: 'Додати новий турнір',
            adminSection: 'Авторизація',
            useful: 'Програми для петанку',
            info: 'Інформація',
            settings: 'Налаштування',
            saved: 'Збережені турніри',
            archivedTournaments: 'Архів турнірів',
            choose: 'Виберіть',
            tournamentName: 'Назва турніру',
            swissSystem: 'Про швейцарську систему',
            howUse: 'Інструкція',
            portal: 'Портал ФПУ',
            show: 'Показати',
            hide: 'Cховати',
            games: 'Ігри',
            thankMe: 'Якщо вам подобається користуватися цією програмкою, можете подякувати мені тут',
            draw: 'Жеребкування',
            stat: 'Статистика',
            training: 'Тренування',
            status: 'Статус',
            active: 'Активний',
            finished: 'Завершений',
            notStarted: 'Не розпочато',
            teamsCount: 'Команди',
            timeLimit: 'Обмеження часу',
            places: 'місця',
            teamsLabel: 'команд',
        },
        help: {
            title: 'Програма для жеребкування турнірів з петанку',
            description: 'Ця програма полегшить життя петанкістам, які організовують турніри, вболівають за улюблену команду або беруть участь у змаганнях. Для жеребкування вам знадобиться тільки інтернет. Гравцям більше не потрібно стояти біля столика організатора, щоб дізнатися, на якому майданчику та проти кого вони грають, чи знайти себе в турнірній таблиці. Тепер є можливість просто перейти з телефона за посиланням і все перевірити онлайн.',
            feature1: 'Програма жеребкує за швейцарською, круговою, олімпійською системах та супермеле.',
            feature2: 'Мінімум налаштувань.',
            feature3: 'Простий інтерфейс (ну так мені здається).',
            feature4: 'Можливість віддалено переглядати поточний статус турніру.',
            feature5: 'Чіткий алгоритм жеребкування за швейцарською системою. Програма не жеребкує команди рандомно. В цій версії, наприклад, якщо перші 6 команд мають однакову кількість перемог, то в наступному раунді вони зіграють за схемою: 1-6, 2-5, 3-4.',
            howToUseTitle: 'Як користуватися цією програмою',
            howToUse1: 'Для того щоб використовувати програму, треба зареєструвати акаунт. Жодних персональних даних, крім email, не потрібно (та й його ніхто не побачить, навіть я, розробник).',
            howToUse2: 'Користувач може використовувати програму як адміністратор (тільки для українських користувачів). Це дає змогу імпортувати гравців з порталу Федерації петанку України. Пароль я можу видати особисто за запитом.',
            shortTitle: 'Розділ для тих, кому не цікаві деталі',
            shortText: 'Щоб провести стандартний турнір за швейцарською системою + плей-офф, потрібно:',
            shortText1: 'Залогінитись як користувач.',
            shortText2: 'Додати назви команд на вкладці "Команди".',
            shortText3: 'Перейти на вкладку "Поточні ігри", пожеребкувати перший раунд.',
            shortText4: 'Внести результати, зберегти їх.',
            shortText5: 'Пожеребкувати наступні раунди, стільки, скільки ви хочете зіграти.',
            shortText6: 'Перейти на вкладку "Таблиця". Подивитись результати (якщо цікаво).',
            shortText7: 'Вибрати кількість команд, яка гратиме у плей-офф, і натиснути кнопку "Погнали".',
            shortText8: 'На вкладці "Поточні ігри" знову ввести всі результати.',
            shortText9: 'Коли ви внесете результати фіналу, турнір буде завершено. Його можна зберегти у себе в акаунті для історії або видалити з поточних турнірів.',
            shortSummary: 'Далі можна читати тим, кому цікаві "деталі".',
            interfaceTitle: 'Основний інтерфейс',
            interface1: 'Натиснувши на заголовок, можна змінити назву турніру.',
            interface2: 'Вибір системи, за якою буде проводитись турнір.',
            interface3: 'Тільки для адміністраторів: можливість імпортувати команди з порталу ФПУ. Для цього потрібно ввести останні цифри з URL-адреси турніру на порталі (наприклад, ',
            interface4: 'Назва команди (наприклад, прізвище капітана), яка буде додана в список команд після натискання "Додати".',
            interface5: 'Налаштування, чи слід використовувати рейтинг при жеребкуванні першого раунду.',
            tournamentControlsTitle: 'Керування турніром',
            tournamentControls1: 'Базові опції - налаштування турніру, можливість його зберегти, завершити або видалити.',
            tournamentControls2: 'Зберегти турнір можна тільки тоді, коли він завершений. Завершеним турнір вважається, коли внесені результати фіналу або натиснута кнопка "Завершити турнір".',
            tournamentControls3: 'Кнопка "Відновити останні команди" корисна, якщо ви вже пожеребкували перший раунд змагань і зрозуміли, що забули додати якусь команду, або якусь команду треба видалити. Додайте новий турнір і натисніть цю кнопку. Команди з попереднього турніру стануть доступними. Про те, як створити новий турнір, читайте в останньому пункті цієї інструкції.',
            mainTabs: 'Основні розділи',
            mainTabs1: 'Список команд, можливість додати чи видалити команду (до того, як пожеребкували перший раунд або будь-коли, якщо грається супермеле).',
            mainTabs2: 'Поточне жеребкування і внесення результатів.',
            mainTabs3: 'Результати всіх зіграних ігор.',
            mainTabs4: 'Підсумкова таблиця після кожного раунду і результати всього турніру.',
            preferences: 'Ті самі "мінімум налаштувань"',
            preferences1: 'Ці налаштування зовсім необов\'язкові.',
            preferences2: 'Інколи потрібно змінити результат технічної перемоги. Можна зробити це тут.',
            preferences3: 'Це налаштування може бути корисним, якщо ви граєте, наприклад, турнір серед клубів, де можливий результат 31:0.',
            drawResults: 'Жеребкування і результати',
            drawResultsText: 'Це найважливіша кнопка. Вона генерує суперників на кожен наступний раунд. У програмі ви не задаєте кількість раундів, які треба зіграти. Теоретично ви не зможете пожеребкувати більше раундів, ніж кількість команд на турнірі. Але при швейцарській системі треба бути обережним, якщо ви проводите турнір при невеликій кількості команд, але з відносно великою кількістю раундів. В якийсь момент програма не зможе виконати всі умови швейцарки і не зведе пари команд. Це може статися, якщо ви захочете провести, умовно, 7 турів при кількості команд не більше 12 (або 5 турів при 8). Тож ретельно продумайте систему, коли проводите такі турніри.',
            drawResults1: 'Кнопка, щоб перетасувати доріжки. Програма не слідкує за тим, чи грала одна команда декілька ігор на одній і тій самій доріжці. Ця функція корисна при невеликій кількості команд (загалом розподілення доріжок рандомне, крім плей-офф).',
            drawResults2: 'Компактніше відображення списку поточних ігор. Доступне тільки на мобільних пристроях.',
            drawResults3: 'Дуже важлива кнопка! Якщо ви помилились при внесенні результату, то є можливість змінити попередній раунд. Кнопка з\'являється після того, як ви пожеребкували наступний раунд. Ви можете виправити ТІЛЬКИ попередній раунд.',
            ranking: 'Ранкінг',
            rankingSwiss1: 'Підсумкова таблиця при швейцарській системі визначається за такими критеріями:',
            rankingSwiss2: 'Кількість перемог.',
            rankingSwiss3: 'Коефіцієнт Бухгольця (сума перемог суперників).',
            rankingSwiss4: 'Коефіцієнт малого Бухгольця (сума бухгольців суперників).',
            rankingSwiss5: 'Різниця набраних/пропущених очок.',
            rankingSwiss6: 'Після кожного раунду можна почати грати турнір за олімпійською системою (на виліт). Оберіть кількість кращих команд, з яких буде згенерована сітка плей-офф.',
            rankingSwiss7: 'Якщо вибрати цю галочку, то автоматично згенерується новий турнір, в який додадуться команди, що не вийшли у плей-офф.',
            rankingRound1: 'Якщо турнір грається за круговою системою, то підсумкова таблиця формується за такими критеріями:',
            rankingRound2: 'Кількість перемог.',
            rankingRound3: 'Результат особистої зустрічі (якщо команди грали між собою).',
            rankingRound4: 'Загальна різниця очок в усіх іграх.',
            rankingRound5: 'Але якщо кількість перемог однакова у трьох чи більше команд, то місця між цими командами розподіляються таким чином:',
            rankingRound6: 'Кількість перемог тільки у групі з цими командами.',
            rankingRound7: 'Різниця очок у групі з цими командами.',
            rankingRound8: 'Загальна різниця очок в усіх іграх.',
            playOff: 'Плей-офф',
            playOffText: 'Якщо турнір грається за олімпійською системою, то на вкладці "Поточні ігри" є можливість подивитись сітку плей-офф. Програма дозволяє жеребкувати максимум 64 команди за олімпійською системою.',
            roundSystem: 'Кругова система',
            roundSystemText: 'Вибираючи кругову систему турніру, можна автоматично розбити команди на групи. Для цього треба вибрати кількість команд в групі (система автоматично округлить кількість груп). Якщо групи не плануються, то треба вибрати ту кількість команд, яка зареєстрована.',
            roundSystemText1: 'Я рекомендую грати турнір з групами, якщо вам виходить зробити кількість команд в групах однаковою.',
            remoteControl: 'Віддалене керування',
            remoteControl1: 'Одна із основних фіч програми (ідея належить Олександру Ковалю) - можливість будь-кому переглядати поточне жеребкування і результати. Потрібне тільки посилання на турнір.',
            remoteControl2: 'Відкрити згенероване посилання на турнір. Це посилання можна розіслати всім учасникам турніру чи вболівальникам.',
            remoteControl3: 'Можна написати повідомлення, яке бачитимуть всі, хто зайде за посиланням. Корисно вписати інформацію про систему розіграшу, таймінги турніру чи побажати всім успіху.',
            remoteView: 'Віддалений перегляд',
            remoteViewText: 'Перейшовши за згенерованим посиланням, можна побачити таку інформацію:',
            remoteView1: 'Повідомлення, написане організатором турніру.',
            remoteView2: 'Поточні ігри турніру.',
            remoteView3: 'Вкладка з усіма попередніми результатами.',
            remoteView4: 'Вкладка з підсумковою таблицею турніру.',
            finishedTournament: 'Завершений турнір',
            finishedTournament1: 'Після того, як турнір завершено, будуть згенеровані фінальні результати на вкладці "Таблиця".',
            finishedTournament2: 'Також ви зможете зберегти результати турніру. Вони будуть доступні в меню, поки ви їх звідти не видалите.',
            finishedTournament3: 'Натиснувши кнопку "Скопіювати результати", ви можете скопіювати результати турніру в текстовому вигляді та надіслати їх адміністратору порталу ФПУ чи поділитися ними у месенджері.',
            tournamentsControlsTitle: 'Керування турнірами',
            tournamentsControls1: 'Додати новий турнір до поточного списку змагань.',
            tournamentsControls2: 'Переключатися між турнірами можна тут (або в мобільному меню, якщо використовуєте мобільний телефон).',
            tournamentsControls3: 'Одночасно в роботі може бути не більше 10 турнірів, тому слід видаляти неактуальні змагання.',
            thanksMessage: 'Дякую за ваш час. Питання, зауваження та пропозиції можна надсилати на',
            thanksMessagePost: 'пошту',
            thanksMessageOr: 'або у',
            thanksMessageMessenger: 'месенджер',
            pressBtnSeeInterface: 'Натиснувши цю кнопку, ви побачите такий інтерфейс:',
            "training": {
                "title": "Тренування",
                "description": "Цей модуль розроблений для відслідковування тренувального процесу. Дозволяє створювати вправи для тренувань, записувати та аналізувати їх результати.",
                "exerciseListTitle": "Сторінка списку вправ",
                "exerciseList": {
                    "add": "Перехід на сторінку додавання нової вправи",
                    "list": "Список створених вправ",
                    "delete": "Видалити вправу",
                    "viewResults": "Подивитись всі результати конкретної вправи",
                    "startTraining": "Почати тренування по конкретній вправі"
                },
                "addExerciseTitle": "Сторінка додавання нової вправи",
                "addExerciseDescription": "Зазвичай люба вправа складається з певної кількості кидків на певну кількість дистанцій. Комбінація цих варіантів дозволяє зробити будь-який варіант тренувальної вправи",
                "addExercise": {
                    "back": "Повернутись до списку вправ",
                    "name": "Назва вправи, як вона буде виглядати в загальному списку",
                    "distances": "Дистанції на які буде виконуватись вправа",
                    "throws": "Кількість кидків на кожну дистанцію",
                    "series": "Тут можна назвати кожну серію. Таким чином ви можете зробити комплексну вправу. Як приклад - змагання з тиру. Коли під по факту ви виконуєте три різні вправи. Приклад створення - в кінці сторінки",
                    "scoring": "Як буде оцінюватися кожен кидок. Можна вибрати логічне значення (влучив / не влучив, поставив / не поставив). Або оцінювати кожен кидок певною кількістю очок.",
                    "scenario": "Якщо вибрати логічне значення, то доступна опція вибору сценарію тренування. При позитивному - всі кидки за замовчуванням будуть вказані, як успішні і навпаки",
                    "order": "Коли є кілька дистанцій і певна кількість кидків на цю дистанцію, то можна провести тренування в різному порядку. Спочатку кинути серію з, наприклад, 10 кидків на одну дистанцію, потім 10 кидків на наступну і т.д. Або можна кидати по одному кидку на кожну дистанцію."
                },
                "trainingProcessTitle": "Сторінка процесу тренування",
                "trainingProcess": {
                    "inputResult": "Тут вводиться результат кидка",
                    "navigation": "Навігація по кидкам чи дистанціям",
                    "finish": "Коли всі кидки виконані, щоб закінчити тренування і порахувати результат, натисність сюди"
                },
                "exerciseResultsTitle": "Сторінка результатів конкретної вправи",
                "exerciseResults": {
                    "average": "Середній результат по вправі за всю історію записів (може бути або відсоток, або конкретна цифра, в залежності від вибраного значення результату кидка)",
                    "byDistance": "Результати по кожній дистанції окремо",
                    "history": "Результати кожного тренування в хронологічному порядку"
                }
            },
            "stat": {
                "title": "Статистика",
                "description": "Дозволяє рахувати статистику в іграх з петанку та аналізувати дані по багатьом критеріям.",
                "settings": {
                    "title": "Налаштування гри",
                    "description": "Із основних налаштувань треба вказати тільки назву гри та формат гри (триплет, дуплет чи тет). А також бажано вказати гравців.",
                    "gameName": "Назва гри як вона буде відображатись в списку.",
                    "tags": "Теги гри. Це ключові слова яким можна описати гру і завдяки яким можна буде в майбутньому фільтрувати дані. Наприклад, вам може бути цікаво як ви зіграли в іграх конкретного турніру. Або ви хочете аналізувати статистику по різним майданчикам. Управляти тегами можна натиснувши кнопку \"Показати теги\".",
                    "mode": "Режим. Швидкий режим був зроблений, щоб було комфортніше записувати статистику під час гри як гравець. Це дозволяє менше часу заглядати в телефон. Детальніше нижче.",
                    "showStats": "Якщо поставите цю галку, то цифри статистики будуть показуватись під час гри. Тобто по ним можна приймати рішення щодо заміни гравця. Якщо ви записуєте статистику як гравець - це може впливати на ваші думки під час гри.",
                    "scoringSystem": "Вибрати систему підрахунку. На даному етапі можна рахувати по простій системі або по французькій. На даному етапі аналіз доступний тільки для простої системи.",
                    "scenario": "Сценарій гри. Тут можна вказати який результат кидку буде вказаний за замовчуванням. Якщо ви граєте як топові гравці світу, то вказуйте позитивний сценарій."
                },
                "tracking": {
                    "title": "Процес ведення статистики",
                    "distance": "Кожен раунд можна вказати на яку дистанцію грають гравці. Вибирати не обов'язково. Але потім при аналізі статистики можна буде фільтрувати дані по дистанціям. Це задає дистанцію відразу для всіх кидків в цьому раунді. Якщо хочете змінити відстань для конкретного кидка, дивіться 7 пункт.",
                    "teamStats": "Поточна статистика команди у відсотках та в загальному (буде показуватись тільки якщо вибрана галка \"Як тренер\").",
                    "playerStats": "Поточна статистика гравця (буде показуватись тільки якщо вибрана галка \"Як тренер\").",
                    "shotsSeries": "Серія кидків гравця (зелений - результативний кидок, червоний - нерезультативний кидок, синій - каро (тільки при тирі)).",
                    "roundPoints": "Скільки очок виграла команда в результаті зіграного раунду.",
                    "highlight": "Зелений знак оклику показує, що це каро при тирі або поінт, при якому заграло 2 кулі.",
                    "contextMenu": "Контекстне меню кидка. Показується при довгому натисканні на результат кидка (більше ніж пів секунди). Можна вказати додаткову ефективність кидка (при результативному шуті це означатиме каро, при промаху це означатиме вибиту свою кулю, при поінті це може значити або підбита своя куля або переміщений кошонет при якому заграло більше ніж одна куля). Також можна видалити кидок (актуально при швидкому режимі гри, коли був вибитий кошонет і не всі кулі були кинуті). Також можна змінити відстань конкретного кидка (актуально коли під час гри кошонет був переміщений).",
                    "shotType": "Тип і результат кидку. Перелючається простим натисканням.",
                    "negativeHighlight": "Червоний знак оклику показує вибиту свою кулю при тирі або при поінті, якщо в результаті кидка заграла чужа куля.",
                    "navigation": "Навігація між раундами."
                },
                "result": {
                    "title": "Результат гри",
                    "finalScore": "Результат гри.",
                    "teamPerformance": "Кінцева результативність гри (командна).",
                    "shotsPerRound": "Результативні кулі за кожний раунд (рахуються коректно тільки тоді, коли ви вказуєте в статистиці результативний кидок як той, що \"зіграв\"). Це досить специфічний показник, який не кожному потрібен, насправді).",
                    "roundPoints": "Скільки очок виграла команда кожного раунду.",
                    "playerSeries": "Серії кидків кожного гравця.",
                    "playerPerformance": "Індивідуальна результативність гравця по результату гри."
                },
                "modes": {
                    "title": "Режими та сценарії",
                    "simple": "Простий режим. Перший клік - зробити кидок активним. Це рахується як кидок, який виконаний.",
                    "fastModePositive": "Швидкий режим. На початку раунду всі кидки будуть записані як виконані. На скріні нижче - швидкий режим та ПОЗИТИВНИЙ сценарій. Тобто за замовчуванням всі кидки результативні.",
                    "fastModeNegative": "А ось нижче вже НЕГАТИВНИЙ сценарій. Поки що в Україні він перемагає.",
                    "fastModeDescription": "Швидкий режим дозволяє вести статистику не відволікаючись на запис КОЖНОГО кидку. Зроблений, як вже вказано вище, щоб легше було писати дані під час гри."
                },
                "tags": {
                    "title": "Теги",
                    "description": "Теги - це ключові слова, якими можна описувати ігри. Можна створювати і видаляти теги.",
                    "usage": "Для кожної гри можна додати необмежену кількість тегів (це можна зробити як на початку гри, так і вже потім, коли гра давно записана). Це дозволяє фільтрувати ігри по цим тегам і аналізувати статистику відповідно до цих тегів. Наприклад, ви можете додати тег \"Твердий майданчик\" і потім дивитись статистику тільки на твердих майданчиках. Тут тільки ваша фантазія."
                },
                "substitutions": {
                    "title": "Заміни",
                    "description": "В процесі гри можна зробити заміну гравця. Треба заховерити на прізвище гравця і з'явиться кнопка, натиснувши на яку відкриється модальне вікно з можливістю ввести прізвище нового гравця."
                },
                "archive": {
                    "title": "Архів",
                    "description": "На цій сторінці зберігаються всі записані ігри.",
                    "filterTags": "Теги по яким можна фільтрувати ігри.",
                    "gameName": "Назва гри. Можна видалити гру, але не можна змінити назву.",
                    "recordDate": "Дата, коли була гра записана.",
                    "addedTags": "Доданий тег до гри.",
                    "addTag": "Можливість додати додатковий тег до гри вже після того, як вона записана."
                },
                "analysis": {
                    "title": "Аналіз",
                    "description": "В цьому блоці можна подивитись детальну статистику по конкретному гравцю.",
                    "selectPlayer": "Вибрати гравця по якому дивитись статистику.",
                    "selectPeriod": "Вибрати період за який буде показана статистика.",
                    "selectFormat": "Вибрати формат гри по якому показувати статистику.",
                    "selectTag": "Вибрати тег по якому фільтрувати статистику.",
                    "selectDistance": "Вибрати дистанцію по якій показувати статистику.",
                    "result": "Результат в результаті вибраних фільтрів.",
                    "charts": "Графіки. Динаміка статистики окремо по поінтам та шутам."
                },
                exampleCreation: "Приклад створення вправи для тиру",
                exampleCreationText: "З такими налаштуваннями ви створите вправу для запису результатів тренувань за правилами класичного тиру"
            }
        },
        stat: {
            archive: 'Архів',
            enterName: 'Введіть назву гри',
            mode: 'Режим',
            scenario: 'Сценарій',
            system: 'Система',
            format: 'Формат',
            team: 'Команда',
            add: 'Додати',
            classic: 'Класичний',
            fast: 'Швидкий',
            simple: 'Проста',
            french: 'Французьська (A, B, ...)',
            positive: 'Позитивний',
            negative: 'Негативний',
            asCoach: 'Як тренер',
            start: 'Старт',
            prev: 'Попередній',
            next: 'Наступний',
            newGame: 'Нова гра',
            finishGame: 'Завершити гру',
            removeMan: 'Видалити цей мен',
            score: 'Рахунок',
            man: 'Мен',
            back: 'Назад',
            analysis: 'аналіз',
            everyManRes: 'Результат кожного раунду',
            resBoules: 'Мен',
            winBoules: 'Мен',
            series: 'Серії',
            all: 'Всі',
            points: 'Поінти',
            tirs: 'Шути',
            howManyPoints: 'Вкажіть скільки очок взяла команда',
            onlyLogin: 'Ви можете рахувати статистику тільки як залогінений користувач',
            total: 'Всього',
            changePlayer: 'Замінити гравця',
            enterPlayerName: 'Введіть ім\'я гравця',
            nothingShow: 'Нічого немає',
            findPlayer: 'Знайти гравця',
            choosePeriod: 'Вибрати період',
            chooseOnly: 'Показати тільки для ',
            clear: 'Очистити',
            noStat: 'Немає статистики для таких фільтрів',
            whatDistance: 'Яка дистанція?',
            important: 'Важливі кидки',
            games: 'ігор',
            gameTags: 'Теги гри',
            addTag: 'Додати тег',
            showTags: 'Показати',
            hideTags: 'Сховати',
            tags: 'теги',
            playerName: 'Гравець',
            team1Label: 'Команда 1',
            team2Label: 'Команда 2',
        },
        messages: {
            sent: 'Надіслано!',
            checkEmail: 'Перевірте вашу пошту',
            error: 'Помилка',
            somethingWrong: 'Щось пішло не так',
            missingEmail: 'Введіть email',
            invalidEmail: 'Невірний email',
            noAccount: 'Немає акаунту з таким email',
            incorrectPassword: 'Невірний пароль',
            passwordMismatch: 'Паролі не збігаються',
            weakPassword: 'Пароль має бути не менше 6 символів',
            cantDraw: 'Неможливо жеребкувати',
            someError: 'Сталася помилка',
            cantDrawRound: 'Неможливо жеребкувати цей раунд',
            tooManyGames: 'Забагато ігор для швейцарки з такою кількістю команд',
            chooseCorrectTeams: 'Оберіть правильну кількість команд у групі',
            success: 'Успішно',
            resultsSaved: 'Ваші результати збережено',
            teamExists: 'Така команда вже зареєстрована! Змініть назву команди',
            enterFields: 'Заповніть поля для додавання команди',
            awesome: 'Чудово!',
            statsSaved: 'Статистику збережено',
            failedLoadTags: 'Не вдалося завантажити теги',
            exercisesLoaded: 'Вправи успішно завантажено',
            noExercisesFound: 'Не знайдено вправ',
            info: 'Інформація',
            failedLoadData: 'Не вдалося завантажити дані',
            exerciseRemoved: 'Вправу успішно видалено',
            notAllResults: 'Не всі результати',
            someAttemptsNotWritten: 'Деякі спроби не записані',
            youAreOffline: 'Ви офлайн',
            trainingSavedBrowser: 'Ваше тренування збережено в браузері. Збережіть його, коли будете онлайн',
            exerciseSaved: 'Вправу збережено',
            protocolCopied: 'Протокол скопійовано в буфер',
            cantCopyProtocol: 'Не вдалося скопіювати протокол',
            tagSaved: 'Тег збережено',
            tagUpdated: 'Тег оновлено',
            removed: 'Видалено',
            tournamentRemoved: 'Турнір видалено',
            notAvailable: 'Недоступно',
            maxTournaments: 'Ви можете створити максимум 10 турнірів. Видаліть один, щоб додати новий',
            saved: 'Збережено',
            tournamentSavedList: 'Збережені турніри можна знайти в меню',
            tournamentRemovedSaved: 'Турнір видалено зі збережених',
            tournamentDataSaved: 'Дані турніру збережено',
            failedSaving: 'Помилка при збереженні',
            removeExercise: 'Видалити цю вправу?',
            tournamentNotActive: 'Турнір не активний',
            noArchivedTournaments: 'Ваші архівовані турніри з\'являться тут після того, як ви їх завершите та збережете',
            gameRemoved: 'Гру успішно видалено',
            tagRemoved: 'Тег успішно видалено',
            failedSaveData: 'Не вдалося зберегти дані',
            tournamentPinned: 'Цей турнір буде відкриватись за замовчуванням',
            tournamentUnpinned: 'Турнір відкріплено',
            preferencesSaved: 'Налаштування збережено',
        },
        training: {
            addEx: 'Додати вправу',
            exList: 'Список вправ',
            toList: 'Назад до списку',
            serieLength: 'кількість серій',
            distances: 'дистанції',
            asLogin: 'Ви можете рахувати тренувальну статистику тільки як зареєстрований користувач',
            addExToBegin: 'Додайте вправи, щоб почати тренування',
            viewResults: 'Подивитись результати',
            startTraining: 'Почати тренування',
            enterExName: 'Введіть назву вправи',
            serieQuantity: 'Кількість кидків у вправі на кожну дистанцію',
            nameSerie: 'Назвати кожну серію?',
            throwValue: '"Ціна" кидка',
            logical: 'Логічна (влучив / не влучив)',
            exScenario: 'Сценарій вправи',
            distFirst: 'Спочатку кидки по дистанціям',
            finishTraining: 'Закінчити тренування',
            attempt: 'кидок',
            meters: 'метрів',
            noResults: 'Поки немає результатів',
            points: 'Очки',
            distance: 'дистанція',
            exGradedText: 'Ця вправа оцінюється по набраним очкам, а не по відсоткам',
            average: 'Середній результат за весь час',
        }
    }
}